// English / Kiswahili strings for Kampasika Biz. Hostel owners are the
// audience, so every operator-facing screen has both.
// t(lang, key, vars) → string, with {name} placeholders.

const COPY = {
  en: {
    brand: "Kampasika Biz",
    tagline: "Run your hostel. Rent is paid straight to you.",
    back: "Back",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    cancel: "Cancel",
    continue: "Continue",
    copy: "Copy",
    copied: "Copied",
    optional: "optional",
    loading: "Loading…",
    openKampasika: "Open Kampasika",
    language: "Kiswahili",

    signInTitle: "Sign in with your Kampasika account",
    signInBody: "Kampasika Biz uses the same account as the Kampasika app. Sign in there, then come back to this page.",
    signInButton: "Go to Kampasika to sign in",

    welcomeTitle: "Bring your hostel to Kampasika Biz",
    welcomeBody: "Open your hostel on Kampasika in one minute — free. Students find your rooms, apply and sign leases online, and pay rent straight to you. Kampasika never holds your money.",
    welcomePoints: [
      "Open today — no documents, no waiting for approval",
      "Students find and apply for your rooms on Kampasika",
      "Rent is paid straight to your own M-Pesa, Lipa or bank number",
      "See who has paid and who hasn't, and download a statement",
    ],
    businessName: "Business or hostel name",
    contactName: "Your full name",
    contactPhone: "Phone number",
    startSetup: "Open my business",

    statusLabel: {
      draft: "Setting up",
      in_review: "In review",
      needs_changes: "Changes needed",
      live: "Live",
      suspended: "Paused",
    },
    progress: "{percent}% ready",
    checklistTitle: "Get ready to collect rent",
    stepState: { done: "Done", waiting: "Waiting", todo: "To do", blocked: "Later" },
    steps: {
      profile: { title: "Business profile", body: "Name, registration, TIN and contact details." },
      documents: { title: "Verified badge documents", body: "Optional. Kampasika checks them and your rooms show “Verified”." },
      settlement: { title: "Where your money lands", body: "The bank or mobile money account pawaPay pays out to." },
      application: { title: "Apply to pawaPay", body: "Open your own pawaPay merchant account." },
      sandbox: { title: "Connect sandbox", body: "Paste the sandbox API token pawaPay gives you." },
      test: { title: "Send a test payment", body: "Prove a payment reaches your pawaPay account." },
      live: { title: "Go live", body: "Connect your production token. Kampasika switches you on." },
      payto: { title: "Where students pay you", body: "Your own M-Pesa, Lipa or bank number. Students pay it directly and you confirm each payment." },
    },
    submitForReview: "Ask Kampasika to switch on online payments",
    submitHint: "Fill in the business profile and where your money lands, then ask Kampasika to switch online payments on.",
    submitted: "Asked. We'll check and switch online payments on — you'll get a notification.",
    changesNeeded: "Kampasika asked for changes:",
    liveBanner: "Online payments are on. Students can pay rent online and it goes straight to your account.",
    suspendedBanner: "Your Kampasika Biz account is paused. Contact Kampasika for help.",

    // Profile
    businessType: "Type of business",
    businessTypes: { company: "Registered company", sole_proprietor: "Business name (sole proprietor)", individual: "Individual owner (with TIN)", unregistered: "Not registered yet — students pay me directly" },
    brelaNumber: "BRELA registration number",
    tin: "TIN",
    contactEmail: "Email",
    region: "Region",
    area: "Area / street",
    nearUni: "Nearest university",
    propertyCount: "Number of hostels / buildings",
    bedCount: "Total beds",
    requiredNote: "Fields without “optional” are needed for online payments.",

    // Documents
    docTypes: {
      brela: { title: "BRELA certificate", body: "Certificate of incorporation or business name registration." },
      tin: { title: "TIN certificate", body: "From TRA." },
      ownerId: { title: "Owner's ID", body: "NIDA card, passport or driving licence of the owner / director." },
      licence: { title: "Business licence", body: "If you have one." },
    },
    upload: "Upload",
    replace: "Replace",
    uploading: "Uploading…",
    view: "View",
    notRequired: "Not required for your business type",
    fileRules: "Photo or PDF, up to 10 MB.",
    fileBadType: "Please choose a photo or a PDF.",
    fileTooBig: "That file is over 10 MB.",
    docsReview: { approved: "Approved by Kampasika", changes_requested: "Kampasika asked you to re-upload", pending: "Waiting for Kampasika review" },

    // Settlement
    settlementIntro: "pawaPay pays collected money out to this account. Kampasika only records it here so we can help you — the account itself is set up with pawaPay.",
    settlementMethod: "Settlement account type",
    settlementMethods: { bank: "Bank account", mobile_money: "Mobile money wallet" },
    institution: "Bank or network",
    institutionPlaceholder: "e.g. CRDB, NMB, NBC, M-Pesa",
    accountName: "Account name",
    accountNameHint: "Must match your business name or the owner's name.",
    confirmedWithPawapay: "I will give these same account details to pawaPay",
    noAccountNumber: "We don't ask for your account number — that goes only to pawaPay.",

    // Application
    applicationIntro: "pawaPay opens merchant accounts for registered, compliant businesses. Your account is yours: rent settles to you, and you can see every payment in your own pawaPay dashboard.",
    applicationChecklistTitle: "Have these ready when you apply",
    applicationChecklist: [
      "Your BRELA registration and TIN",
      "Owner / director ID",
      "The settlement account from the previous step",
      "A short description: student accommodation, rent collection by mobile money",
    ],
    applicationHowTitle: "How it goes",
    applicationHow: [
      "Apply on pawapay.io and complete their business checks.",
      "pawaPay gives you sandbox (test) access — connect it in the next step.",
      "After approval, pawaPay gives you a production token for real money.",
    ],
    applicationConfirmNote: "pawaPay's exact requirements can change — follow what their onboarding team asks for.",
    openPawapay: "Open pawapay.io",
    applicationStatus: "Where are you with pawaPay?",
    applicationStatuses: { not_started: "Not applied yet", submitted: "Applied, waiting for pawaPay", approved: "Approved by pawaPay" },
    merchantName: "Merchant name on pawaPay",
    applicationNote: "Notes (reference number, contact person…)",

    // Connect
    sandboxIntro: "In your pawaPay sandbox dashboard, create an API token and paste it here. We check it with pawaPay, then store it encrypted — nobody at Kampasika can read it.",
    productionIntro: "When pawaPay approves you for live payments, create a production API token and paste it here.",
    apiToken: "API token",
    connect: "Connect",
    connecting: "Checking with pawaPay…",
    connectedAs: "Connected as {name}",
    connectedToken: "Token ending …{last4}",
    disconnect: "Disconnect",
    callbackTitle: "Set your callback URL",
    callbackBody: "In the pawaPay dashboard, set the deposit callback URL to this address so payments update here automatically:",
    signedCallbacksOff: "Tip: payments still update without callbacks — you can press “Check status” on any payment.",

    // Test
    testIntro: "Send a small sandbox payment to a test number. Nothing real is charged. When it completes, you've proved payments reach your own pawaPay account.",
    testPhone: "Phone number",
    testProvider: "Network",
    testAmount: "Amount (TZS)",
    sendTest: "Send test payment",
    sending: "Sending…",
    checkStatus: "Check status",
    testStatus: { pending: "Waiting for the payment to complete…", paid: "Test payment completed", failed: "Test payment failed" },
    tryAgain: "Try again",

    // Live
    liveIntro: "Last step. Connect your production token, then submit. Kampasika checks everything and switches you live.",
    waitingForKampasika: "Everything's in. Kampasika is reviewing — you'll get a notification.",
    needsSubmit: "Connect production, then submit for review from the home screen.",

    // Admin
    adminTitle: "Kampasika Biz — Admin",
    adminFilterAll: "All",
    adminEmpty: "No businesses yet.",
    adminApproveDocs: "Approve documents",
    adminRequestChanges: "Request changes",
    adminSetLive: "Set live",
    adminSuspend: "Pause",
    adminReopen: "Back to review",
    adminNote: "Note to the business (optional)",
    adminHelpConnect: "Help connect a token (in person)",
    adminOnlyNotice: "Only Kampasika admins can open this page.",
    lastUpdated: "Updated",


    // Navigation
    navSetup: "Setup",
    navApplications: "Applications",

    // Applications (step 2)
    applicationsTitle: "Applications",
    applicationsIntro: "Students apply for your rooms from Kampasika. Review them here and contact the ones you want.",
    applicationsLocked: "Applications open once Kampasika has approved your documents.",
    acceptingOn: "Accepting applications",
    acceptingOff: "Not accepting applications",
    acceptingHint: "When on, students see an “Apply” button on your rooms in Kampasika.",
    appFilters: { new: "New", shortlisted: "Shortlisted", approved: "Approved", closed: "Closed" },
    appStatus: { submitted: "New", shortlisted: "Shortlisted", approved: "Approved", rejected: "Rejected", withdrawn: "Withdrawn" },
    appEmpty: "No applications here yet.",
    appNewCount: "{count} new",
    appRoom: "Room",
    appMoveIn: "Move-in",
    appStay: "Stay",
    appStayOptions: { semester: "One semester", academic_year: "Academic year", monthly: "Month to month", other: "Other" },
    appUniversity: "University",
    appCourse: "Course / year",
    appReg: "Reg. number",
    appPhone: "Phone",
    appMessage: "Message",
    appApplied: "Applied",
    appCall: "Call",
    appWhatsApp: "WhatsApp",
    appShortlist: "Shortlist",
    appApprove: "Approve",
    appReject: "Reject",
    appNotePlaceholder: "Note to the student (optional)",
    appHistory: "History",
    appDecided: "Student notified.",
    appNextLease: "Next: leases for approved students are coming in the next update.",

    // Leases (step 3)
    navLeases: "Leases",
    leasesTitle: "Leases",
    leasesIntro: "Create a lease from an approved application. The student reads it and signs in Kampasika.",
    leasesEmpty: "No leases yet. Approve an application, then tap “Create lease”.",
    leaseStatus: { sent: "Waiting for signature", pending_fee: "Signed · fee pending", signed: "Signed", declined: "Declined", cancelled: "Cancelled" },
    leaseFilters: { sent: "Waiting", signed: "Signed", closed: "Closed" },
    templateCardTitle: "Your lease template",
    templateCardBody: "Start from the Kampasika standard lease and edit it to match your house rules.",
    templateStandard: "Standard lease",
    templateCustom: "Your edited lease",
    editTemplate: "Edit template",
    templateTitle: "Lease template",
    templateIntro: "Edit any clause, add your own or remove ones you don't need. Words in {{double braces}} are filled in automatically for each student.",
    templateLegalNote: "This standard lease is a plain-language starting point, not legal advice. Have a lawyer check it before you rely on it.",
    templateLanguage: "Lease language",
    languages: { en: "English", sw: "Kiswahili" },
    clauseTitle: "Heading",
    clauseBody: "Text",
    addClause: "+ Add clause",
    removeClause: "Remove",
    moveUp: "↑",
    moveDown: "↓",
    resetTemplate: "Reset to standard lease",
    placeholdersTitle: "Placeholders you can use",
    defaultsTitle: "Default terms",
    defaultsIntro: "Pre-filled on every new lease. You can still change them per student.",
    rentPeriod: "Rent period",
    rentPeriods: { month: "Per month", semester: "Per semester", year: "Per year" },
    rent: "Rent (TZS)",
    deposit: "Deposit (TZS)",
    dueDay: "Rent due by day",
    noticeDays: "Notice period (days)",
    utilities: "Water & electricity",
    utilitiesHint: "Completes “Water and electricity are …”, e.g. “included in the rent” or “paid by the tenant through their own LUKU meter”.",
    utilitiesHintSw: "Completes “Maji na umeme …”, e.g. “yamejumuishwa kwenye kodi”.",
    startDate: "Start date",
    endDate: "End date",
    extraTerms: "Extra terms for this student",
    createLease: "Create lease",
    createLeaseTitle: "New lease",
    createLeaseIntro: "Check the terms, preview, then send. The student gets a notification to read and sign.",
    preview: "Preview",
    sendLease: "Send lease to student",
    viewLease: "View lease",
    leaseFor: "Lease for {name}",
    leaseRef: "Lease {ref}",
    landlord: "Landlord",
    tenant: "Tenant",
    summary: "Summary",
    perPeriod: "per {period}",
    issuedBy: "Issued by {name} on {date}",
    signedBy: "Signed by {name} on {date}",
    signatureDetails: "Typed-name signature · version {hash}",
    printLease: "Print / save as PDF",
    cancelLease: "Withdraw lease",
    cancelReason: "Reason (optional)",
    signTitle: "Sign this lease",
    signIntro: "Read the whole lease first. Signing is binding — only sign if you agree with every clause.",
    agreeBox: "I have read this lease and I agree to its terms.",
    typeName: "Type your full name to sign",
    signButton: "Sign lease",
    signing: "Signing…",
    declineButton: "Decline",
    declineReason: "Tell the landlord why (optional)",
    declineConfirm: "Decline lease",
    signedBanner: "This lease is signed by both parties.",
    declinedBanner: "The student declined this lease.",
    cancelledBanner: "This lease was withdrawn by the landlord.",
    waitingBanner: "Waiting for the student to sign.",
    leaseNotFound: "This lease doesn't exist or isn't yours.",
    backToKampasika: "Back to Kampasika",
    applicationLease: "Lease",

    // Rent (step 4)
    navRent: "Rent",
    rentTitle: "Rent",
    rentIntro: "Every signed lease becomes a rent schedule. Students pay online straight to your account, or pay your number and report it; record cash yourself.",
    tileCollected: "Collected this month",
    tileOutstanding: "Overdue balance",
    tileOverdue: "Tenants behind",
    tileDueSoon: "Due in 7 days",
    occupancyTitle: "Occupancy",
    occupied: "{occupied} of {total} rooms occupied",
    otherRooms: "Other rooms",
    noRooms: "No rooms listed yet. Add rooms in the Kampasika app (My Properties).",
    onlinePayTitle: "Online rent payments",
    onlinePayLive: "On — students can pay online, straight into your account.",
    onlinePayOff: "Off — you'll go live after Kampasika's review. Until then, record payments yourself.",
    sandboxRentLabel: "Test mode: let students pay in the pawaPay sandbox",
    sandboxRentHint: "For trying the flow with test numbers only — no real money moves. Turn it off before real tenants pay.",
    chargeFilters: { confirm: "To confirm", overdue: "Overdue", soon: "Due soon", open: "All unpaid", paid: "Paid" },
    chargeStatus: { due: "Due", partial: "Part paid", paid: "Paid", waived: "Waived", overdue: "Overdue" },
    noCharges: "Nothing here.",
    dueOn: "Due {date}",
    balance: "Balance",
    paid: "Paid",
    payments: "Payments",
    recordPayment: "Record a payment",
    amount: "Amount (TZS)",
    method: "Method",
    methods: { cash: "Cash", bank: "Bank", mobile_money: "Mobile money (outside Kampasika)", other: "Other", pawapay: "Online (mobile money)", pawapay_sandbox: "Online (test)" },
    reference: "Reference / receipt no.",
    paidOn: "Paid on",
    waive: "Waive",
    waiveNote: "Reason (shown to the student)",
    rentScheduleTitle: "Rent & payments",
    payNow: "Pay",
    payTitle: "Pay with mobile money",
    payTestBadge: "TEST MODE — no real money",
    payNotAvailable: "Online payment isn't switched on for this landlord yet. Pay them directly — they'll record it here.",
    payPhone: "Your mobile money number",
    payNetwork: "Network",
    payAmount: "Amount (TZS)",
    paySend: "Send payment request",
    payWaiting: "Check your phone and approve the payment…",
    payDone: "Payment received ✓",
    payFailed: "The payment didn't go through.",
    totalDue: "Still to pay",
    // Kampasika fees (placement fee)
    feesTitle: "Kampasika fees",
    feesIntro: "Kampasika charges a small placement fee only when a student you found through Kampasika signs a lease. Rent always goes to you — this fee is separate.",
    feeHowTitle: "How it works",
    feeRulePercent: "{percent}% of one month's rent",
    feeRuleFixed: "{amount} per room filled",
    feeHowRule: "Fee per room filled: {rule}.",
    feeHowWhen: "You pay only when the student signs the lease in Kampasika — not for listings, applications or visits.",
    feeHowFree: "Your first {count} placements are free ({left} left).",
    feeHowDue: "Pay within {days} days by mobile money. If a fee is unpaid {grace} days after the due date, new leases pause until it's paid — your signed leases and rent keep working.",
    feeHowRent: "Semester or yearly rent counts as one month's share (semester ÷ 6, year ÷ 12).",
    feeNoneYet: "No fees are charged at the moment.",
    feeTileDue: "To pay",
    feeTilePlacements: "Rooms filled",
    feeTilePaid: "Fees paid",
    feeTileFreeLeft: "Free placements left",
    feeEmpty: "No fees yet. When a student signs a lease, it shows here.",
    feeToPay: "To pay",
    feeHistory: "History",
    feeStatus: { due: "Due", late: "Late", blocking: "Overdue", paid: "Paid", free: "Free", waived: "Waived" },
    feeFreeLabel: "Free placement",
    feeBasis: "Fee",
    feeListPrice: "Normal fee",
    feePay: "Pay",
    feeWaiveNote: "Reason for waiving (the business sees it)",
    leaseRefShort: "Lease",
    feeNoticeTitle: "Kampasika placement fee",
    feeNoticeBody: "When the student signs this lease, Kampasika's placement fee of {amount} is due within {days} days. Rent still goes to you.",
    feeNoticeFree: "This one is free — one of your free placements (normally {amount}).",
    feesDueTitle: "Kampasika fee to pay: {amount}",
    feesDueBody: "Open Fees to pay by mobile money",
    feesBlockingTitle: "New leases are paused",
    feesBlockingBody: "A Kampasika fee ({amount}) is overdue. Pay it to issue new leases",
    homeFees: "Kampasika fees",
    homeFeesSub: "Placement fees and payments",
    adminPricingTitle: "Owner placement fee (optional — off for now)",
    adminPricingEnabled: "Charge a placement fee",
    adminPricingEnabledHint: "When on, every lease a student signs creates an invoice to the business. Existing leases aren't charged.",
    adminPricingType: "Fee type",
    adminPricingPercent: "% of one month's rent",
    adminPricingFixed: "Fixed amount per room",
    adminPricingFree: "Free placements per business",
    adminPricingDueDays: "Days to pay",
    adminPricingGrace: "Grace days before new leases pause",
    adminPricingEnv: "Kampasika pawaPay account",
    adminPricingExample: "Example: a TZS 100,000/month room → fee {amount}.",
    adminPricingEnvHint: "Switch to production only after the PAWAPAY_API_TOKEN secret holds your production token.",
    adminInvoicesTitle: "Fee invoices",
    adminInvoicesTotals: "Collected {paid} · outstanding {due}",
    serviceFeeOpTitle: "Kampasika service fee (paid by the student)",
    serviceFeeOpBody: "When the student signs, they pay Kampasika a service fee of {amount}. You receive 100% of the rent — no fee for you.",
    serviceFeeTitle: "Kampasika service fee",
    serviceFeeExplain: "Kampasika's fee for finding this room and handling your lease ({percent}% of the lease rent, capped so it's cheaper than a dalali). You pay it right after signing — it isn't rent, and the landlord still gets their full rent.",
    serviceFeeOpWaiting: "The student signed. The lease becomes active when they pay the Kampasika service fee ({amount}). You can withdraw it if they don't pay.",
    serviceFeePayTitle: "Pay the service fee to activate your lease",
    serviceFeePayBody: "You've signed ✓. Pay the Kampasika service fee of {amount} by mobile money and your lease becomes active.",
    pendingFeeStudentBanner: "Signed — pay the Kampasika service fee below to activate your lease.",
    signAndPayButton: "Sign & pay service fee",
    serviceFeeBasis: "{percent}% of the lease rent ({total}), capped",
    feeKindPlacement: "Owner placement fee",
    feeKindService: "Student service fee",
    adminServiceTitle: "Student service fee (Kampasika revenue)",
    adminServiceEnabled: "Charge students a service fee when they sign",
    adminServiceEnabledHint: "Shown on the room and the lease before signing. The lease activates once it's paid. Leases already issued aren't affected.",
    adminServicePercent: "% of the whole lease rent",
    adminServiceCap: "Cap: % of one month's rent (0 = no cap)",
    adminServiceExample: "For a TZS 90,000/month room: 3 months → {m3} · 6 months → {m6} · 10 months → {m10}.",
    termsNoticeStudent: "By signing you accept Kampasika's Terms, including the service fee and not making this tenancy outside Kampasika.",
    termsNoticeOwner: "Tenancies with students you met through Kampasika must go through Kampasika (see Terms).",
    termsLink: "Terms",
    navOverview: "Overview",
    navSetupFull: "Settings",
    dashSetupLinkSub: "Payment number, Verified badge, online payments",
    dashSubtitle: "here's how your hostel is doing",
    dashActApplications: "Applications",
    dashActRecord: "Record a payment",
    dashSetupTitle: "Finish setting up online rent payments",
    dashSetupBody: "Students can already apply. Finish the pawaPay steps to collect rent online.",
    dashKpiOccupancy: "Occupancy",
    dashKpiOccupancySub: "{occupied} of {total} rooms occupied",
    dashKpiCollectedSub: "Rent received this month",
    dashKpiUp: "▲ {pct}% vs this time last month",
    dashKpiDown: "▼ {pct}% vs this time last month",
    dashKpiBehind: "{count} tenants behind",
    dashAllPaid: "Everyone is up to date",
    dashKpiApplications: "New applications",
    dashKpiDueSoon: "{amount} due in the next 7 days",
    dashKpiNothingDue: "No rent due in the next 7 days",
    dashChartTitle: "Rent collected",
    dashChartSub: "Last 6 months · all buildings",
    dashChartAria: "Column chart of rent collected in each of the last six months",
    dashPayments: "{count} payments",
    dashEmptyRooms: "{count} empty — students on Kampasika can apply",
    dashAttention: "Needs your attention",
    dashAllClear: "Nothing waiting. Rent is up to date and there are no new applications.",
    dashDaysLate: "{days} days late",
    dashNewApp: "New application",
    dashRecent: "Recent payments",
    dashSeeAll: "See all",
    dashNoPayments: "No payments yet.",
    demoBanner: "Demo with sample data — look around, nothing here is real or saved.",
    demoCta: "Start with your hostel",
    demoLink: "See a demo with sample data",
    unregisteredHint: "No problem. Students pay rent to your own number and you confirm each payment in Kampasika. Online payments can come later when you register.",
    liveBannerDirect: "You're live. Students pay rent to your own number and report it; confirm each payment in Rent.",
    payToTitle: "Direct payments to you",
    payToIntro: "Students will see this number on their lease with the exact amount and a reference. They pay it from their own phone, tell Kampasika the transaction code, and you confirm when you see the money. Kampasika never touches the money.",
    payToMethod: "How students pay you",
    payToMethods: { mobile_money: "Mobile money number", lipa: "Lipa number (till)", bank: "Bank account" },
    payToNetwork: "Network",
    payToBank: "Bank",
    payToPhone: "Phone number",
    payToLipa: "Lipa number",
    payToAccount: "Account number",
    payToName: "Name students will see",
    payToNameHint: "Exactly as it appears when they pay, so they know it's you.",
    payToNote: "Extra instruction",
    payToNotePlaceholder: "e.g. Use your room number as the reference",
    payToPrivacy: "Only your tenants with a signed lease see this number.",
    payToCardBody: "Students pay here and report it; you confirm below.",
    payToCardEmpty: "Add the number students pay you (M-Pesa, Lipa or bank). It's shown only to your tenants, on their lease.",
    payToEdit: "Change number",
    payToAdd: "Add payment number",
    onlinePayDirect: "Students pay your own number and report it; you confirm each payment. Automatic online payments are optional — set them up in Settings when you're ready.",
    claimTitle: "Student says they paid {amount}",
    claimDetails: "Code {code} · paid {date}. Check your M-Pesa / account, then confirm.",
    claimConfirm: "Confirm received",
    claimReject: "Not received",
    claimRejectNote: "Tell the student why (optional)",
    rentIntroDirect: "Every signed lease becomes a rent schedule. Students pay your own number and report it — confirm each payment here, or record cash yourself.",
    claimsBanner: "Payments to confirm: {count}",
    claimsBannerBody: "Students reported paying you directly. Check your account and confirm.",
    payDirectIntro: "Pay the landlord directly to their number below, then tap “I've paid” and enter the transaction code. The landlord confirms and it's recorded here.",
    payDirectButton: "Pay {amount} directly",
    directPayTo: "Send to",
    directReference: "Reference",
    directNoNumber: "The landlord hasn't added a payment number yet. Pay them the usual way, then report it here.",
    reportTitle: "After paying, tell the landlord",
    reportCode: "Transaction code (from the SMS)",
    reportButton: "I've paid",
    reportDone: "Thanks — the landlord has been told. It shows as paid once they confirm.",
    claimWaitingStudent: "You reported paying {amount} (code {code}). Waiting for the landlord to confirm.",
    claimWaitingOwner: "The student reported paying {amount}. Confirm it on the Rent tab.",
    claimRejectedStudent: "The landlord didn't find your payment (code {code})",
    dashClaim: "Says they paid · code {code}",
    proofLabel: "Screenshot of the payment",
    proofAttach: "Attach screenshot or photo",
    proofRemove: "Remove",
    proofHint: "Add the transaction code, a screenshot, or both — the landlord uses them to find your payment.",
    proofOrCode: "Enter the transaction code or attach a screenshot.",
    proofNotImage: "Choose a photo or screenshot.",
    proofView: "View screenshot",
    proofShort: "screenshot",
    welcomeRegistered: "Is your hostel registered?",
    welcomePayTitle: "Where students pay you",
    welcomePayBody: "Your own number. Students see it on their lease with the exact amount, pay from their phone and report it; you confirm. The money never passes through Kampasika.",
    welcomePayLater: "No number yet? Leave it empty and add it later in Settings.",
    welcomeTermsNote: "By opening your business you accept Kampasika's",
    settingsTitle: "Settings",
    settingsIntro: "Your business is open. Only the payment number matters for rent — everything else is optional.",
    settingsBusiness: "Business",
    edit: "Edit",
    settingsNeeded: "Needed for rent",
    verifyTitle: "Verified badge",
    verifyState: {"done": "Verified", "waiting": "Being checked", "changes": "Needs changes", "ready": "Ready to send", "todo": "Not started"},
    verifyBody: "Students trust verified hostels more. Upload your documents and Kampasika checks them — then your rooms show “✓ Verified”.",
    verifyDone: "Your rooms show “✓ Verified” to students.",
    verifyUpload: "Upload documents",
    verifyAsk: "Ask Kampasika to verify",
    onlineTitle: "Online payments",
    onlineOn: "On",
    onlineBody: "Let students pay rent online and have it confirmed automatically, straight into your own merchant account. For registered businesses.",
    onlineManual: "Online payments need a registered business (BRELA or TIN). Until then students pay your number directly — that already works.",
    onlineRegistered: "I've registered — update my details",
    onlineSetupLink: "Set up online payments",
    verifiedPill: "Verified",
    openPill: "Open",
    navStatement: "Statement",
    startTitle: "Get started",
    startBody: "Your business is open. Two things and students can start paying you:",
    startCreated: "Business created",
    startPayTo: "Add the number students pay you",
    startPayToSub: "M-Pesa, Lipa or bank — shown only to your tenants.",
    startRooms: "List your rooms",
    startRoomsSub: "Add your hostel and rooms in the Kampasika app — they appear here automatically.",
    startRoomsBtn: "List rooms in Kampasika",
    startShare: "Share your rooms",
    startShareSub: "Open a room and tap Share to send its link on WhatsApp. Students apply, you approve and send the lease.",
    adminFilterVerify: "Verify requests",
    stmtTitle: "Statement",
    stmtIntro: "every rent payment you've received",
    stmtMonth: "Month",
    stmtAllTime: "All time",
    stmtPrint: "Print",
    stmtExport: "Export CSV",
    stmtTotal: "Total received",
    stmtCount: "Payments",
    stmtSource: {"online": "Paid online", "confirmed": "Confirmed by you", "recorded": "Recorded by you"},
    stmtEmpty: "No payments yet for this period.",
    stmtDate: "Date",
    stmtTenant: "Tenant",
    stmtRoom: "Room",
    stmtFor: "For",
    stmtMethod: "Method",
    stmtHow: "How recorded",
    stmtReference: "Reference",
    stmtAmount: "Amount",
    stmtNote: "This is Kampasika's record of rent paid to you. The money itself went straight to you — check it against your M-Pesa or bank statement.",
    genericError: "Something went wrong. Please try again.",
  },

  sw: {
    brand: "Kampasika Biz",
    tagline: "Endesha hosteli yako. Kodi inalipwa moja kwa moja kwako.",
    back: "Rudi",
    save: "Hifadhi",
    saving: "Inahifadhi…",
    saved: "Imehifadhiwa",
    cancel: "Ghairi",
    continue: "Endelea",
    copy: "Nakili",
    copied: "Imenakiliwa",
    optional: "si lazima",
    loading: "Inapakia…",
    openKampasika: "Fungua Kampasika",
    language: "English",

    signInTitle: "Ingia kwa akaunti yako ya Kampasika",
    signInBody: "Kampasika Biz inatumia akaunti ile ile ya programu ya Kampasika. Ingia huko, kisha rudi kwenye ukurasa huu.",
    signInButton: "Nenda Kampasika kuingia",

    welcomeTitle: "Leta hosteli yako Kampasika Biz",
    welcomeBody: "Fungua hosteli yako kwenye Kampasika kwa dakika moja — bure. Wanafunzi wanaona vyumba vyako, wanaomba na kusaini mikataba mtandaoni, na wanakulipa kodi moja kwa moja. Kampasika haishiki pesa zako.",
    welcomePoints: [
      "Fungua leo — bila nyaraka, bila kusubiri idhini",
      "Wanafunzi wanaona na kuomba vyumba vyako kwenye Kampasika",
      "Kodi inalipwa moja kwa moja kwenye namba yako ya M-Pesa, Lipa au benki",
      "Ona nani amelipa na nani bado, na pakua taarifa ya malipo",
    ],
    businessName: "Jina la biashara au hosteli",
    contactName: "Jina lako kamili",
    contactPhone: "Namba ya simu",
    startSetup: "Fungua biashara yangu",

    statusLabel: {
      draft: "Inaandaliwa",
      in_review: "Inakaguliwa",
      needs_changes: "Marekebisho yanahitajika",
      live: "Iko hewani",
      suspended: "Imesimamishwa",
    },
    progress: "Tayari {percent}%",
    checklistTitle: "Jiandae kupokea kodi",
    stepState: { done: "Imekamilika", waiting: "Inasubiri", todo: "Fanya", blocked: "Baadaye" },
    steps: {
      profile: { title: "Taarifa za biashara", body: "Jina, usajili, TIN na mawasiliano." },
      documents: { title: "Nyaraka za beji ya Imethibitishwa", body: "Si lazima. Kampasika inazikagua na vyumba vyako vinaonyesha “Imethibitishwa”." },
      settlement: { title: "Pesa zinaingia wapi", body: "Akaunti ya benki au ya simu ambayo pawaPay itakulipa." },
      application: { title: "Omba pawaPay", body: "Fungua akaunti yako ya mfanyabiashara ya pawaPay." },
      sandbox: { title: "Unganisha sandbox", body: "Bandika tokeni ya majaribio (sandbox) ya pawaPay." },
      test: { title: "Tuma malipo ya majaribio", body: "Thibitisha malipo yanafika kwenye akaunti yako ya pawaPay." },
      live: { title: "Anza rasmi", body: "Unganisha tokeni ya production. Kampasika itakuwasha." },
      payto: { title: "Wanafunzi wanakulipa wapi", body: "Namba yako ya M-Pesa, Lipa au benki. Wanafunzi wanalipa moja kwa moja na wewe unathibitisha kila malipo." },
    },
    submitForReview: "Omba Kampasika iwashe malipo ya mtandaoni",
    submitHint: "Jaza taarifa za biashara na pesa zinaingia wapi, kisha omba Kampasika iwashe malipo ya mtandaoni.",
    submitted: "Umeomba. Tutakagua na kuwasha malipo ya mtandaoni — utapata taarifa.",
    changesNeeded: "Kampasika imeomba marekebisho:",
    liveBanner: "Malipo ya mtandaoni yamewashwa. Wanafunzi wanaweza kulipa kodi mtandaoni na pesa zinaingia moja kwa moja kwenye akaunti yako.",
    suspendedBanner: "Akaunti yako ya Kampasika Biz imesimamishwa. Wasiliana na Kampasika.",

    businessType: "Aina ya biashara",
    businessTypes: { company: "Kampuni iliyosajiliwa", sole_proprietor: "Jina la biashara (mmiliki pekee)", individual: "Mmiliki binafsi (mwenye TIN)", unregistered: "Bado sijasajiliwa — wanafunzi wanilipe moja kwa moja" },
    brelaNumber: "Namba ya usajili BRELA",
    tin: "TIN",
    contactEmail: "Barua pepe",
    region: "Mkoa",
    area: "Eneo / mtaa",
    nearUni: "Chuo kilicho karibu",
    propertyCount: "Idadi ya hosteli / majengo",
    bedCount: "Jumla ya vitanda",
    requiredNote: "Sehemu zisizo na “si lazima” zinahitajika kwa malipo ya mtandaoni.",

    docTypes: {
      brela: { title: "Cheti cha BRELA", body: "Cheti cha usajili wa kampuni au jina la biashara." },
      tin: { title: "Cheti cha TIN", body: "Kutoka TRA." },
      ownerId: { title: "Kitambulisho cha mmiliki", body: "NIDA, pasipoti au leseni ya udereva ya mmiliki / mkurugenzi." },
      licence: { title: "Leseni ya biashara", body: "Kama unayo." },
    },
    upload: "Pakia",
    replace: "Badilisha",
    uploading: "Inapakia…",
    view: "Tazama",
    notRequired: "Haihitajiki kwa aina ya biashara yako",
    fileRules: "Picha au PDF, hadi MB 10.",
    fileBadType: "Tafadhali chagua picha au PDF.",
    fileTooBig: "Faili hilo ni zaidi ya MB 10.",
    docsReview: { approved: "Imeidhinishwa na Kampasika", changes_requested: "Kampasika imeomba upakie tena", pending: "Inasubiri ukaguzi wa Kampasika" },

    settlementIntro: "pawaPay inalipa pesa zilizokusanywa kwenye akaunti hii. Kampasika inaiandika hapa tu ili tukusaidie — akaunti yenyewe inasajiliwa na pawaPay.",
    settlementMethod: "Aina ya akaunti ya kupokea",
    settlementMethods: { bank: "Akaunti ya benki", mobile_money: "Pochi ya pesa ya simu" },
    institution: "Benki au mtandao",
    institutionPlaceholder: "mf. CRDB, NMB, NBC, M-Pesa",
    accountName: "Jina la akaunti",
    accountNameHint: "Lilingane na jina la biashara au la mmiliki.",
    confirmedWithPawapay: "Nitampa pawaPay taarifa hizi hizi za akaunti",
    noAccountNumber: "Hatuombi namba ya akaunti yako — hiyo inaenda kwa pawaPay pekee.",

    applicationIntro: "pawaPay inafungua akaunti za wafanyabiashara kwa biashara zilizosajiliwa na zinazofuata taratibu. Akaunti ni yako: kodi inaingia kwako, na unaona kila malipo kwenye dashibodi yako ya pawaPay.",
    applicationChecklistTitle: "Andaa hivi unapoomba",
    applicationChecklist: [
      "Usajili wako wa BRELA na TIN",
      "Kitambulisho cha mmiliki / mkurugenzi",
      "Akaunti ya kupokea kutoka hatua iliyopita",
      "Maelezo mafupi: malazi ya wanafunzi, kukusanya kodi kwa pesa ya simu",
    ],
    applicationHowTitle: "Inavyokwenda",
    applicationHow: [
      "Omba kwenye pawapay.io na ukamilishe ukaguzi wao wa biashara.",
      "pawaPay itakupa ufikiaji wa sandbox (majaribio) — uunganishe hatua inayofuata.",
      "Ukiidhinishwa, pawaPay itakupa tokeni ya production kwa pesa halisi.",
    ],
    applicationConfirmNote: "Mahitaji ya pawaPay yanaweza kubadilika — fuata wanachokuomba timu yao.",
    openPawapay: "Fungua pawapay.io",
    applicationStatus: "Umefika wapi na pawaPay?",
    applicationStatuses: { not_started: "Bado sijaomba", submitted: "Nimeomba, nasubiri pawaPay", approved: "Nimeidhinishwa na pawaPay" },
    merchantName: "Jina la mfanyabiashara kwenye pawaPay",
    applicationNote: "Maelezo (namba ya kumbukumbu, mtu wa mawasiliano…)",

    sandboxIntro: "Kwenye dashibodi ya sandbox ya pawaPay, tengeneza API token na uibandike hapa. Tunaikagua na pawaPay, kisha tunaihifadhi kwa usimbaji fiche — hakuna mtu Kampasika anayeweza kuisoma.",
    productionIntro: "pawaPay ikikuidhinisha kwa malipo halisi, tengeneza API token ya production na uibandike hapa.",
    apiToken: "API token",
    connect: "Unganisha",
    connecting: "Inakagua na pawaPay…",
    connectedAs: "Imeunganishwa kama {name}",
    connectedToken: "Tokeni inayoishia …{last4}",
    disconnect: "Tenganisha",
    callbackTitle: "Weka callback URL",
    callbackBody: "Kwenye dashibodi ya pawaPay, weka deposit callback URL kuwa anwani hii ili malipo yasasishwe hapa yenyewe:",
    signedCallbacksOff: "Kidokezo: malipo yanasasishwa hata bila callback — unaweza kubonyeza “Angalia hali” kwenye malipo yoyote.",

    testIntro: "Tuma malipo madogo ya sandbox kwa namba ya majaribio. Hakuna pesa halisi inayokatwa. Yakikamilika, umethibitisha malipo yanafika kwenye akaunti yako ya pawaPay.",
    testPhone: "Namba ya simu",
    testProvider: "Mtandao",
    testAmount: "Kiasi (TZS)",
    sendTest: "Tuma malipo ya majaribio",
    sending: "Inatuma…",
    checkStatus: "Angalia hali",
    testStatus: { pending: "Inasubiri malipo yakamilike…", paid: "Malipo ya majaribio yamekamilika", failed: "Malipo ya majaribio yameshindwa" },
    tryAgain: "Jaribu tena",

    liveIntro: "Hatua ya mwisho. Unganisha tokeni ya production, kisha tuma. Kampasika itakagua kila kitu na kukuwasha.",
    waitingForKampasika: "Kila kitu kimekamilika. Kampasika inakagua — utapata taarifa.",
    needsSubmit: "Unganisha production, kisha tuma ikaguliwe kutoka ukurasa wa mwanzo.",

    adminTitle: "Kampasika Biz — Admin",
    adminFilterAll: "Zote",
    adminEmpty: "Bado hakuna biashara.",
    adminApproveDocs: "Idhinisha nyaraka",
    adminRequestChanges: "Omba marekebisho",
    adminSetLive: "Washa",
    adminSuspend: "Simamisha",
    adminReopen: "Rudisha ukaguzini",
    adminNote: "Ujumbe kwa biashara (si lazima)",
    adminHelpConnect: "Saidia kuunganisha tokeni (ana kwa ana)",
    adminOnlyNotice: "Ni admin wa Kampasika pekee wanaoweza kufungua ukurasa huu.",
    lastUpdated: "Imesasishwa",


    navSetup: "Usajili",
    navApplications: "Maombi",

    applicationsTitle: "Maombi",
    applicationsIntro: "Wanafunzi wanaomba vyumba vyako kupitia Kampasika. Yakague hapa na uwasiliane na unaowataka.",
    applicationsLocked: "Maombi yanafunguliwa baada ya Kampasika kuidhinisha nyaraka zako.",
    acceptingOn: "Unapokea maombi",
    acceptingOff: "Hupokei maombi",
    acceptingHint: "Ukiwasha, wanafunzi wanaona kitufe cha “Omba” kwenye vyumba vyako Kampasika.",
    appFilters: { new: "Mapya", shortlisted: "Waliochaguliwa", approved: "Yaliyokubaliwa", closed: "Yaliyofungwa" },
    appStatus: { submitted: "Jipya", shortlisted: "Amechaguliwa", approved: "Limekubaliwa", rejected: "Limekataliwa", withdrawn: "Limeondolewa" },
    appEmpty: "Bado hakuna maombi hapa.",
    appNewCount: "{count} mapya",
    appRoom: "Chumba",
    appMoveIn: "Kuhamia",
    appStay: "Muda",
    appStayOptions: { semester: "Semester moja", academic_year: "Mwaka wa masomo", monthly: "Kila mwezi", other: "Nyingine" },
    appUniversity: "Chuo",
    appCourse: "Kozi / mwaka",
    appReg: "Namba ya usajili",
    appPhone: "Simu",
    appMessage: "Ujumbe",
    appApplied: "Aliomba",
    appCall: "Piga simu",
    appWhatsApp: "WhatsApp",
    appShortlist: "Chagua awali",
    appApprove: "Kubali",
    appReject: "Kataa",
    appNotePlaceholder: "Ujumbe kwa mwanafunzi (si lazima)",
    appHistory: "Historia",
    appDecided: "Mwanafunzi amejulishwa.",
    appNextLease: "Ifuatayo: mikataba kwa wanafunzi waliokubaliwa inakuja kwenye toleo lijalo.",

    navLeases: "Mikataba",
    leasesTitle: "Mikataba",
    leasesIntro: "Tengeneza mkataba kutoka kwenye ombi lililokubaliwa. Mwanafunzi anausoma na kuusaini ndani ya Kampasika.",
    leasesEmpty: "Bado hakuna mikataba. Kubali ombi, kisha bonyeza “Tengeneza mkataba”.",
    leaseStatus: { sent: "Unasubiri sahihi", pending_fee: "Umesainiwa · ada inasubiriwa", signed: "Umesainiwa", declined: "Umekataliwa", cancelled: "Umefutwa" },
    leaseFilters: { sent: "Inasubiri", signed: "Imesainiwa", closed: "Imefungwa" },
    templateCardTitle: "Kiolezo chako cha mkataba",
    templateCardBody: "Anza na mkataba wa kawaida wa Kampasika na uuhariri ulingane na kanuni za nyumba yako.",
    templateStandard: "Mkataba wa kawaida",
    templateCustom: "Mkataba wako uliohariri",
    editTemplate: "Hariri kiolezo",
    templateTitle: "Kiolezo cha mkataba",
    templateIntro: "Hariri kifungu chochote, ongeza vyako au ondoa usivyohitaji. Maneno ndani ya {{mabano mawili}} yanajazwa yenyewe kwa kila mwanafunzi.",
    templateLegalNote: "Mkataba huu wa kawaida ni mwanzo kwa lugha rahisi, si ushauri wa kisheria. Mwombe mwanasheria aukague kabla ya kuutegemea.",
    templateLanguage: "Lugha ya mkataba",
    languages: { en: "English", sw: "Kiswahili" },
    clauseTitle: "Kichwa",
    clauseBody: "Maandishi",
    addClause: "+ Ongeza kifungu",
    removeClause: "Ondoa",
    moveUp: "↑",
    moveDown: "↓",
    resetTemplate: "Rudisha mkataba wa kawaida",
    placeholdersTitle: "Maneno ya kujazwa unayoweza kutumia",
    defaultsTitle: "Masharti ya kawaida",
    defaultsIntro: "Yanajazwa kwenye kila mkataba mpya. Bado unaweza kuyabadilisha kwa kila mwanafunzi.",
    rentPeriod: "Kipindi cha kodi",
    rentPeriods: { month: "Kwa mwezi", semester: "Kwa semester", year: "Kwa mwaka" },
    rent: "Kodi (TZS)",
    deposit: "Amana (TZS)",
    dueDay: "Kodi ilipwe kabla ya siku",
    noticeDays: "Muda wa taarifa (siku)",
    utilities: "Maji na umeme",
    utilitiesHint: "Inakamilisha “Water and electricity are …”, mf. “included in the rent”.",
    utilitiesHintSw: "Inakamilisha “Maji na umeme …”, mf. “yamejumuishwa kwenye kodi” au “yanalipwa na mpangaji kupitia mita yake ya LUKU”.",
    startDate: "Tarehe ya kuanza",
    endDate: "Tarehe ya kuisha",
    extraTerms: "Masharti ya ziada kwa mwanafunzi huyu",
    createLease: "Tengeneza mkataba",
    createLeaseTitle: "Mkataba mpya",
    createLeaseIntro: "Kagua masharti, angalia hakikisho, kisha tuma. Mwanafunzi atapata taarifa ya kuusoma na kuusaini.",
    preview: "Hakikisho",
    sendLease: "Tuma mkataba kwa mwanafunzi",
    viewLease: "Tazama mkataba",
    leaseFor: "Mkataba wa {name}",
    leaseRef: "Mkataba {ref}",
    landlord: "Mwenye Nyumba",
    tenant: "Mpangaji",
    summary: "Muhtasari",
    perPeriod: "kwa {period}",
    issuedBy: "Umetolewa na {name} tarehe {date}",
    signedBy: "Umesainiwa na {name} tarehe {date}",
    signatureDetails: "Sahihi kwa kuandika jina · toleo {hash}",
    printLease: "Chapisha / hifadhi PDF",
    cancelLease: "Futa mkataba",
    cancelReason: "Sababu (si lazima)",
    signTitle: "Saini mkataba huu",
    signIntro: "Soma mkataba wote kwanza. Kusaini kunakufunga kisheria — saini tu kama unakubali kila kifungu.",
    agreeBox: "Nimesoma mkataba huu na ninakubali masharti yake.",
    typeName: "Andika jina lako kamili kusaini",
    signButton: "Saini mkataba",
    signing: "Inasaini…",
    declineButton: "Kataa",
    declineReason: "Mweleze mwenye nyumba sababu (si lazima)",
    declineConfirm: "Kataa mkataba",
    signedBanner: "Mkataba huu umesainiwa na pande zote mbili.",
    declinedBanner: "Mwanafunzi amekataa mkataba huu.",
    cancelledBanner: "Mkataba huu umefutwa na mwenye nyumba.",
    waitingBanner: "Unasubiri mwanafunzi asaini.",
    leaseNotFound: "Mkataba huu haupo au si wako.",
    backToKampasika: "Rudi Kampasika",
    applicationLease: "Mkataba",

    navRent: "Kodi",
    rentTitle: "Kodi",
    rentIntro: "Kila mkataba uliosainiwa unakuwa ratiba ya kodi. Wanafunzi wanalipa mtandaoni moja kwa moja kwenye akaunti yako, au wanalipa namba yako na kuripoti; andika mwenyewe malipo ya taslimu.",
    tileCollected: "Zilizokusanywa mwezi huu",
    tileOutstanding: "Deni lililochelewa",
    tileOverdue: "Wapangaji waliochelewa",
    tileDueSoon: "Zinadaiwa ndani ya siku 7",
    occupancyTitle: "Ukaliaji",
    occupied: "Vyumba {occupied} kati ya {total} vimekaliwa",
    otherRooms: "Vyumba vingine",
    noRooms: "Bado hakuna vyumba. Ongeza vyumba kwenye programu ya Kampasika (My Properties).",
    onlinePayTitle: "Malipo ya kodi mtandaoni",
    onlinePayLive: "Yamewashwa — wanafunzi wanaweza kulipa mtandaoni, moja kwa moja kwenye akaunti yako.",
    onlinePayOff: "Yamezimwa — utawashwa baada ya ukaguzi wa Kampasika. Hadi hapo, andika malipo mwenyewe.",
    sandboxRentLabel: "Hali ya majaribio: wanafunzi walipe kwenye sandbox ya pawaPay",
    sandboxRentHint: "Kwa kujaribu tu kwa namba za majaribio — hakuna pesa halisi inayohamishwa. Zima kabla wapangaji halisi hawajalipa.",
    chargeFilters: { confirm: "Za kuthibitisha", overdue: "Zimechelewa", soon: "Zinakaribia", open: "Zote zisizolipwa", paid: "Zimelipwa" },
    chargeStatus: { due: "Inadaiwa", partial: "Imelipwa sehemu", paid: "Imelipwa", waived: "Imesamehewa", overdue: "Imechelewa" },
    noCharges: "Hakuna kitu hapa.",
    dueOn: "Inadaiwa {date}",
    balance: "Salio",
    paid: "Imelipwa",
    payments: "Malipo",
    recordPayment: "Andika malipo",
    amount: "Kiasi (TZS)",
    method: "Njia",
    methods: { cash: "Taslimu", bank: "Benki", mobile_money: "Pesa ya simu (nje ya Kampasika)", other: "Nyingine", pawapay: "Mtandaoni (pesa ya simu)", pawapay_sandbox: "Mtandaoni (majaribio)" },
    reference: "Kumbukumbu / namba ya risiti",
    paidOn: "Tarehe ya malipo",
    waive: "Samehe",
    waiveNote: "Sababu (mwanafunzi ataiona)",
    rentScheduleTitle: "Kodi na malipo",
    payNow: "Lipa",
    payTitle: "Lipa kwa pesa ya simu",
    payTestBadge: "MAJARIBIO — hakuna pesa halisi",
    payNotAvailable: "Malipo mtandaoni bado hayajawashwa kwa mwenye nyumba huyu. Mlipe moja kwa moja — ataandika hapa.",
    payPhone: "Namba yako ya pesa ya simu",
    payNetwork: "Mtandao",
    payAmount: "Kiasi (TZS)",
    paySend: "Tuma ombi la malipo",
    payWaiting: "Angalia simu yako na uidhinishe malipo…",
    payDone: "Malipo yamepokelewa ✓",
    payFailed: "Malipo hayakufanikiwa.",
    totalDue: "Bado kulipa",
    // Ada za Kampasika
    feesTitle: "Ada za Kampasika",
    feesIntro: "Kampasika inatoza ada ndogo ya upangishaji pale tu mwanafunzi uliyempata kupitia Kampasika anaposaini mkataba. Kodi yote inakuja kwako — ada hii ni tofauti.",
    feeHowTitle: "Inavyofanya kazi",
    feeRulePercent: "{percent}% ya kodi ya mwezi mmoja",
    feeRuleFixed: "{amount} kwa kila chumba kilichojazwa",
    feeHowRule: "Ada kwa kila chumba kilichojazwa: {rule}.",
    feeHowWhen: "Unalipa tu mwanafunzi akisaini mkataba ndani ya Kampasika — si kwa kutangaza, maombi wala kutembelea.",
    feeHowFree: "Upangishaji wako {count} wa kwanza ni bure (zimebaki {left}).",
    feeHowDue: "Lipa ndani ya siku {days} kwa pesa ya simu. Ada ikibaki bila kulipwa siku {grace} baada ya tarehe ya mwisho, mikataba mipya inasimama hadi ilipwe — mikataba iliyosainiwa na kodi vinaendelea.",
    feeHowRent: "Kodi ya semester au mwaka inahesabiwa kwa mwezi mmoja (semester ÷ 6, mwaka ÷ 12).",
    feeNoneYet: "Hakuna ada inayotozwa kwa sasa.",
    feeTileDue: "Za kulipa",
    feeTilePlacements: "Vyumba vilivyojazwa",
    feeTilePaid: "Ada zilizolipwa",
    feeTileFreeLeft: "Bure zilizobaki",
    feeEmpty: "Bado hakuna ada. Mwanafunzi akisaini mkataba, itaonekana hapa.",
    feeToPay: "Za kulipa",
    feeHistory: "Historia",
    feeStatus: { due: "Inadaiwa", late: "Imechelewa", blocking: "Imepitiliza", paid: "Imelipwa", free: "Bure", waived: "Imesamehewa" },
    feeFreeLabel: "Upangishaji wa bure",
    feeBasis: "Ada",
    feeListPrice: "Ada ya kawaida",
    feePay: "Lipa",
    feeWaiveNote: "Sababu ya kusamehe (biashara itaiona)",
    leaseRefShort: "Mkataba",
    feeNoticeTitle: "Ada ya upangishaji ya Kampasika",
    feeNoticeBody: "Mwanafunzi akisaini mkataba huu, ada ya Kampasika ya {amount} italipwa ndani ya siku {days}. Kodi bado inakuja kwako.",
    feeNoticeFree: "Huu ni bure — mmoja wa upangishaji wako wa bure (kwa kawaida {amount}).",
    feesDueTitle: "Ada ya Kampasika ya kulipa: {amount}",
    feesDueBody: "Fungua Ada kulipa kwa pesa ya simu",
    feesBlockingTitle: "Mikataba mipya imesimamishwa",
    feesBlockingBody: "Ada ya Kampasika ({amount}) imepitiliza muda. Ilipe ili utoe mikataba mipya",
    homeFees: "Ada za Kampasika",
    homeFeesSub: "Ada za upangishaji na malipo",
    serviceFeeOpTitle: "Ada ya huduma ya Kampasika (inalipwa na mwanafunzi)",
    serviceFeeOpBody: "Mwanafunzi akisaini, analipa Kampasika ada ya huduma ya {amount}. Wewe unapokea kodi yote 100% — hakuna ada kwako.",
    serviceFeeTitle: "Ada ya huduma ya Kampasika",
    serviceFeeExplain: "Ada ya Kampasika kwa kukupatia chumba hiki na kushughulikia mkataba wako ({percent}% ya kodi ya mkataba, yenye kikomo ili iwe nafuu kuliko dalali). Unalipa mara baada ya kusaini — si kodi, na mwenye nyumba anapata kodi yake yote.",
    serviceFeeOpWaiting: "Mwanafunzi amesaini. Mkataba utaanza akilipa ada ya huduma ya Kampasika ({amount}). Unaweza kuufuta asipolipa.",
    serviceFeePayTitle: "Lipa ada ya huduma ili mkataba uanze",
    serviceFeePayBody: "Umesaini ✓. Lipa ada ya huduma ya Kampasika ya {amount} kwa pesa ya simu na mkataba wako utaanza.",
    pendingFeeStudentBanner: "Umesaini — lipa ada ya huduma ya Kampasika hapa chini ili mkataba uanze.",
    signAndPayButton: "Saini na ulipe ada ya huduma",
    serviceFeeBasis: "{percent}% ya kodi ya mkataba ({total}), yenye kikomo",
    feeKindPlacement: "Ada ya mwenye nyumba",
    feeKindService: "Ada ya huduma ya mwanafunzi",
    termsNoticeStudent: "Kwa kusaini unakubali Masharti ya Kampasika, ikiwemo ada ya huduma na kutofanya mkataba huu nje ya Kampasika.",
    termsNoticeOwner: "Mikataba na wanafunzi uliokutana nao kupitia Kampasika lazima ipitie Kampasika (tazama Masharti).",
    termsLink: "Masharti",
    navOverview: "Muhtasari",
    navSetupFull: "Mipangilio",
    dashSetupLinkSub: "Namba ya malipo, beji ya Imethibitishwa, malipo ya mtandaoni",
    dashSubtitle: "hivi ndivyo hosteli yako inavyoendelea",
    dashActApplications: "Maombi",
    dashActRecord: "Andika malipo",
    dashSetupTitle: "Kamilisha usajili wa malipo ya kodi mtandaoni",
    dashSetupBody: "Wanafunzi tayari wanaweza kuomba. Kamilisha hatua za pawaPay ili kupokea kodi mtandaoni.",
    dashKpiOccupancy: "Ukaliaji",
    dashKpiOccupancySub: "Vyumba {occupied} kati ya {total} vimekaliwa",
    dashKpiCollectedSub: "Kodi iliyopokelewa mwezi huu",
    dashKpiUp: "▲ {pct}% ukilinganisha na wakati huu mwezi uliopita",
    dashKpiDown: "▼ {pct}% ukilinganisha na wakati huu mwezi uliopita",
    dashKpiBehind: "Wapangaji {count} wamechelewa",
    dashAllPaid: "Wote wamelipa kwa wakati",
    dashKpiApplications: "Maombi mapya",
    dashKpiDueSoon: "{amount} zinadaiwa ndani ya siku 7",
    dashKpiNothingDue: "Hakuna kodi inayodaiwa siku 7 zijazo",
    dashChartTitle: "Kodi iliyokusanywa",
    dashChartSub: "Miezi 6 iliyopita · majengo yote",
    dashChartAria: "Chati ya kodi iliyokusanywa kila mwezi kwa miezi sita iliyopita",
    dashPayments: "Malipo {count}",
    dashEmptyRooms: "{count} vitupu — wanafunzi wa Kampasika wanaweza kuomba",
    dashAttention: "Yanayohitaji hatua",
    dashAllClear: "Hakuna kinachosubiri. Kodi iko sawa na hakuna maombi mapya.",
    dashDaysLate: "Imechelewa siku {days}",
    dashNewApp: "Ombi jipya",
    dashRecent: "Malipo ya karibuni",
    dashSeeAll: "Ona yote",
    dashNoPayments: "Bado hakuna malipo.",
    demoBanner: "Mfano wenye data za majaribio — angalia kila kitu, hakuna kilicho halisi wala kinachohifadhiwa.",
    demoCta: "Anza na hosteli yako",
    demoLink: "Ona mfano wenye data za majaribio",
    unregisteredHint: "Hakuna shida. Wanafunzi wanalipa kodi kwenye namba yako na wewe unathibitisha kila malipo kwenye Kampasika. Malipo ya mtandaoni yanaweza kuja baadaye ukisajili.",
    liveBannerDirect: "Uko hewani. Wanafunzi wanalipa kodi kwenye namba yako na kuripoti; thibitisha kila malipo kwenye Kodi.",
    payToTitle: "Malipo ya moja kwa moja kwako",
    payToIntro: "Wanafunzi wataona namba hii kwenye mkataba wao pamoja na kiasi kamili na kumbukumbu. Wanalipa kwa simu zao, wanaiambia Kampasika namba ya muamala, na wewe unathibitisha ukiona pesa. Kampasika haigusi pesa hizi.",
    payToMethod: "Wanafunzi wanakulipa vipi",
    payToMethods: { mobile_money: "Namba ya pesa ya simu", lipa: "Namba ya Lipa", bank: "Akaunti ya benki" },
    payToNetwork: "Mtandao",
    payToBank: "Benki",
    payToPhone: "Namba ya simu",
    payToLipa: "Namba ya Lipa",
    payToAccount: "Namba ya akaunti",
    payToName: "Jina wanafunzi watakaloliona",
    payToNameHint: "Kama linavyoonekana wanapolipa, ili wajue ni wewe.",
    payToNote: "Maelekezo ya ziada",
    payToNotePlaceholder: "mf. Tumia namba ya chumba kama kumbukumbu",
    payToPrivacy: "Wapangaji wenye mkataba uliosainiwa pekee ndio wanaona namba hii.",
    payToCardBody: "Wanafunzi wanalipa hapa na kuripoti; wewe unathibitisha hapa chini.",
    payToCardEmpty: "Ongeza namba ambayo wanafunzi wanakulipa (M-Pesa, Lipa au benki). Inaonekana kwa wapangaji wako pekee, kwenye mkataba wao.",
    payToEdit: "Badilisha namba",
    payToAdd: "Ongeza namba ya malipo",
    onlinePayDirect: "Wanafunzi wanalipa namba yako na kuripoti; wewe unathibitisha kila malipo. Malipo ya mtandaoni ya moja kwa moja si lazima — yaweke kwenye Mipangilio ukiwa tayari.",
    claimTitle: "Mwanafunzi anasema amelipa {amount}",
    claimDetails: "Namba {code} · alilipa {date}. Angalia M-Pesa / akaunti yako, kisha thibitisha.",
    claimConfirm: "Thibitisha nimepokea",
    claimReject: "Sijapokea",
    claimRejectNote: "Mweleze mwanafunzi sababu (si lazima)",
    rentIntroDirect: "Kila mkataba uliosainiwa unakuwa ratiba ya kodi. Wanafunzi wanalipa namba yako na kuripoti — thibitisha kila malipo hapa, au andika malipo ya taslimu mwenyewe.",
    claimsBanner: "Malipo ya kuthibitisha: {count}",
    claimsBannerBody: "Wanafunzi wameripoti kukulipa moja kwa moja. Angalia akaunti yako na uthibitishe.",
    payDirectIntro: "Mlipe mwenye nyumba moja kwa moja kwenye namba iliyo hapa chini, kisha bonyeza “Nimelipa” na uweke namba ya muamala. Mwenye nyumba atathibitisha na itaandikwa hapa.",
    payDirectButton: "Lipa {amount} moja kwa moja",
    directPayTo: "Tuma kwa",
    directReference: "Kumbukumbu",
    directNoNumber: "Mwenye nyumba bado hajaweka namba ya malipo. Mlipe kwa njia ya kawaida, kisha ripoti hapa.",
    reportTitle: "Baada ya kulipa, mwambie mwenye nyumba",
    reportCode: "Namba ya muamala (kwenye SMS)",
    reportButton: "Nimelipa",
    reportDone: "Asante — mwenye nyumba amearifiwa. Itaonekana imelipwa akithibitisha.",
    claimWaitingStudent: "Umeripoti kulipa {amount} (namba {code}). Unasubiri mwenye nyumba athibitishe.",
    claimWaitingOwner: "Mwanafunzi ameripoti kulipa {amount}. Thibitisha kwenye Kodi.",
    claimRejectedStudent: "Mwenye nyumba hakuona malipo yako (namba {code})",
    dashClaim: "Anasema amelipa · namba {code}",
    proofLabel: "Picha ya skrini ya malipo",
    proofAttach: "Ambatisha picha ya skrini",
    proofRemove: "Ondoa",
    proofHint: "Weka namba ya muamala, picha ya skrini, au vyote — mwenye nyumba anavitumia kupata malipo yako.",
    proofOrCode: "Weka namba ya muamala au ambatisha picha ya skrini.",
    proofNotImage: "Chagua picha au picha ya skrini.",
    proofView: "Ona picha ya skrini",
    proofShort: "picha ya skrini",
    welcomeRegistered: "Hosteli yako imesajiliwa?",
    welcomePayTitle: "Wanafunzi wanakulipa wapi",
    welcomePayBody: "Namba yako mwenyewe. Wanafunzi wanaiona kwenye mkataba wao pamoja na kiasi kamili, wanalipa kwa simu zao na kuripoti; wewe unathibitisha. Pesa hazipiti Kampasika.",
    welcomePayLater: "Huna namba bado? Iache wazi na uiongeze baadaye kwenye Mipangilio.",
    welcomeTermsNote: "Kwa kufungua biashara yako unakubali",
    settingsTitle: "Mipangilio",
    settingsIntro: "Biashara yako iko wazi. Namba ya malipo pekee ndiyo muhimu kwa kodi — mengine yote si lazima.",
    settingsBusiness: "Biashara",
    edit: "Hariri",
    settingsNeeded: "Inahitajika kwa kodi",
    verifyTitle: "Beji ya Imethibitishwa",
    verifyState: {"done": "Imethibitishwa", "waiting": "Inakaguliwa", "changes": "Marekebisho yanahitajika", "ready": "Tayari kutuma", "todo": "Bado"},
    verifyBody: "Wanafunzi wanaziamini zaidi hosteli zilizothibitishwa. Pakia nyaraka zako na Kampasika itazikagua — kisha vyumba vyako vitaonyesha “✓ Imethibitishwa”.",
    verifyDone: "Vyumba vyako vinaonyesha “✓ Imethibitishwa” kwa wanafunzi.",
    verifyUpload: "Pakia nyaraka",
    verifyAsk: "Omba Kampasika ithibitishe",
    onlineTitle: "Malipo ya mtandaoni",
    onlineOn: "Yamewashwa",
    onlineBody: "Ruhusu wanafunzi walipe kodi mtandaoni na yathibitishwe yenyewe, moja kwa moja kwenye akaunti yako ya mfanyabiashara. Kwa biashara zilizosajiliwa.",
    onlineManual: "Malipo ya mtandaoni yanahitaji biashara iliyosajiliwa (BRELA au TIN). Hadi hapo wanafunzi wanalipa namba yako moja kwa moja — hilo tayari linafanya kazi.",
    onlineRegistered: "Nimesajili — sasisha taarifa zangu",
    onlineSetupLink: "Weka malipo ya mtandaoni",
    verifiedPill: "Imethibitishwa",
    openPill: "Iko wazi",
    navStatement: "Taarifa ya malipo",
    startTitle: "Anza hapa",
    startBody: "Biashara yako iko wazi. Mambo mawili tu, kisha wanafunzi wanaweza kuanza kukulipa:",
    startCreated: "Biashara imefunguliwa",
    startPayTo: "Ongeza namba ambayo wanafunzi wanakulipa",
    startPayToSub: "M-Pesa, Lipa au benki — inaonekana kwa wapangaji wako pekee.",
    startRooms: "Orodhesha vyumba vyako",
    startRoomsSub: "Ongeza hosteli na vyumba vyako kwenye programu ya Kampasika — vitaonekana hapa vyenyewe.",
    startRoomsBtn: "Orodhesha vyumba Kampasika",
    startShare: "Shiriki vyumba vyako",
    startShareSub: "Fungua chumba na ubonyeze Shiriki kutuma kiungo chake WhatsApp. Wanafunzi wanaomba, wewe unakubali na kutuma mkataba.",
    adminFilterVerify: "Maombi ya uthibitisho",
    stmtTitle: "Taarifa ya malipo",
    stmtIntro: "kila malipo ya kodi uliyopokea",
    stmtMonth: "Mwezi",
    stmtAllTime: "Muda wote",
    stmtPrint: "Chapisha",
    stmtExport: "Pakua CSV",
    stmtTotal: "Jumla iliyopokelewa",
    stmtCount: "Malipo",
    stmtSource: {"online": "Mtandaoni", "confirmed": "Umethibitisha", "recorded": "Umeandika mwenyewe"},
    stmtEmpty: "Hakuna malipo bado kwa kipindi hiki.",
    stmtDate: "Tarehe",
    stmtTenant: "Mpangaji",
    stmtRoom: "Chumba",
    stmtFor: "Kwa ajili ya",
    stmtMethod: "Njia",
    stmtHow: "Imeandikwaje",
    stmtReference: "Kumbukumbu",
    stmtAmount: "Kiasi",
    stmtNote: "Hii ni kumbukumbu ya Kampasika ya kodi uliyolipwa. Pesa zenyewe zilikuja moja kwa moja kwako — zilinganishe na taarifa yako ya M-Pesa au benki.",
    genericError: "Kuna tatizo. Tafadhali jaribu tena.",
  },
};

export function t(lang, key, vars) {
  const table = COPY[lang] || COPY.en;
  const value = key.split(".").reduce((obj, part) => (obj == null ? obj : obj[part]), table);
  const fallback = key.split(".").reduce((obj, part) => (obj == null ? obj : obj[part]), COPY.en);
  const out = value ?? fallback ?? key;
  if (typeof out !== "string" || !vars) return out;
  return out.replace(/\{(\w+)\}/g, (_, name) => (vars[name] ?? ""));
}
