// English / Kiswahili strings for Kampasika Biz. Hostel owners are the
// audience, so every operator-facing screen has both.
// t(lang, key, vars) → string, with {name} placeholders.

const COPY = {
  en: {
    brand: "Kampasika Biz",
    tagline: "Run your hostel. Get paid straight to your account.",
    back: "Back",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    cancel: "Cancel",
    continue: "Continue",
    copy: "Copy",
    copied: "Copied",
    optional: "optional",
    loading: "Loading…",
    openKampasika: "Open Kampasika",
    language: "Kiswahili",

    signInTitle: "Sign in with your Kampasika account",
    signInBody: "Kampasika Biz uses the same account as the Kampasika app. Sign in there, then come back to this page.",
    signInButton: "Go to Kampasika to sign in",

    welcomeTitle: "Bring your hostel to Kampasika Biz",
    welcomeBody: "Set up your business once. We help you get your own pawaPay account, so students pay rent by mobile money and the money lands directly with you — Kampasika never holds it.",
    welcomePoints: [
      "Students find and apply for your rooms on Kampasika",
      "Rent is paid by M-Pesa, Airtel Money, Mixx by Yas or HaloPesa",
      "Money settles to your own account, not ours",
      "See who has paid and who hasn't, per property",
    ],
    businessName: "Business or hostel name",
    contactName: "Your full name",
    contactPhone: "Phone number",
    startSetup: "Start setup",

    statusLabel: {
      draft: "Setting up",
      in_review: "In review",
      needs_changes: "Changes needed",
      live: "Live",
      suspended: "Paused",
    },
    progress: "{percent}% ready",
    checklistTitle: "Get ready to collect rent",
    stepState: { done: "Done", waiting: "Waiting", todo: "To do", blocked: "Later" },
    steps: {
      profile: { title: "Business profile", body: "Name, registration, TIN and contact details." },
      documents: { title: "Documents", body: "BRELA certificate, TIN certificate and owner ID." },
      settlement: { title: "Where your money lands", body: "The bank or mobile money account pawaPay pays out to." },
      application: { title: "Apply to pawaPay", body: "Open your own pawaPay merchant account." },
      sandbox: { title: "Connect sandbox", body: "Paste the sandbox API token pawaPay gives you." },
      test: { title: "Send a test payment", body: "Prove a payment reaches your pawaPay account." },
      live: { title: "Go live", body: "Connect your production token. Kampasika switches you on." },
    },
    submitForReview: "Submit to Kampasika for review",
    submitHint: "Finish profile, documents and settlement to submit. You can keep working on pawaPay while we review.",
    submitted: "Submitted. We'll review your business and notify you here.",
    changesNeeded: "Kampasika asked for changes:",
    liveBanner: "You're live. Rent from students now goes straight to your pawaPay account.",
    suspendedBanner: "Your Kampasika Biz account is paused. Contact Kampasika for help.",

    // Profile
    businessType: "Type of business",
    businessTypes: { company: "Registered company", sole_proprietor: "Business name (sole proprietor)", individual: "Individual owner" },
    brelaNumber: "BRELA registration number",
    tin: "TIN",
    contactEmail: "Email",
    region: "Region",
    area: "Area / street",
    nearUni: "Nearest university",
    propertyCount: "Number of hostels / buildings",
    bedCount: "Total beds",
    requiredNote: "Fields without “optional” are required by pawaPay and Kampasika.",

    // Documents
    docTypes: {
      brela: { title: "BRELA certificate", body: "Certificate of incorporation or business name registration." },
      tin: { title: "TIN certificate", body: "From TRA." },
      ownerId: { title: "Owner's ID", body: "NIDA card, passport or driving licence of the owner / director." },
      licence: { title: "Business licence", body: "If you have one." },
    },
    upload: "Upload",
    replace: "Replace",
    uploading: "Uploading…",
    view: "View",
    notRequired: "Not required for your business type",
    fileRules: "Photo or PDF, up to 10 MB.",
    fileBadType: "Please choose a photo or a PDF.",
    fileTooBig: "That file is over 10 MB.",
    docsReview: { approved: "Approved by Kampasika", changes_requested: "Kampasika asked you to re-upload", pending: "Waiting for Kampasika review" },

    // Settlement
    settlementIntro: "pawaPay pays collected money out to this account. Kampasika only records it here so we can help you — the account itself is set up with pawaPay.",
    settlementMethod: "Settlement account type",
    settlementMethods: { bank: "Bank account", mobile_money: "Mobile money wallet" },
    institution: "Bank or network",
    institutionPlaceholder: "e.g. CRDB, NMB, NBC, M-Pesa",
    accountName: "Account name",
    accountNameHint: "Must match your business name or the owner's name.",
    confirmedWithPawapay: "I will give these same account details to pawaPay",
    noAccountNumber: "We don't ask for your account number — that goes only to pawaPay.",

    // Application
    applicationIntro: "pawaPay opens merchant accounts for registered, compliant businesses. Your account is yours: rent settles to you, and you can see every payment in your own pawaPay dashboard.",
    applicationChecklistTitle: "Have these ready when you apply",
    applicationChecklist: [
      "Your BRELA registration and TIN",
      "Owner / director ID",
      "The settlement account from the previous step",
      "A short description: student accommodation, rent collection by mobile money",
    ],
    applicationHowTitle: "How it goes",
    applicationHow: [
      "Apply on pawapay.io and complete their business checks.",
      "pawaPay gives you sandbox (test) access — connect it in the next step.",
      "After approval, pawaPay gives you a production token for real money.",
    ],
    applicationConfirmNote: "pawaPay's exact requirements can change — follow what their onboarding team asks for.",
    openPawapay: "Open pawapay.io",
    applicationStatus: "Where are you with pawaPay?",
    applicationStatuses: { not_started: "Not applied yet", submitted: "Applied, waiting for pawaPay", approved: "Approved by pawaPay" },
    merchantName: "Merchant name on pawaPay",
    applicationNote: "Notes (reference number, contact person…)",

    // Connect
    sandboxIntro: "In your pawaPay sandbox dashboard, create an API token and paste it here. We check it with pawaPay, then store it encrypted — nobody at Kampasika can read it.",
    productionIntro: "When pawaPay approves you for live payments, create a production API token and paste it here.",
    apiToken: "API token",
    connect: "Connect",
    connecting: "Checking with pawaPay…",
    connectedAs: "Connected as {name}",
    connectedToken: "Token ending …{last4}",
    disconnect: "Disconnect",
    callbackTitle: "Set your callback URL",
    callbackBody: "In the pawaPay dashboard, set the deposit callback URL to this address so payments update here automatically:",
    signedCallbacksOff: "Tip: payments still update without callbacks — you can press “Check status” on any payment.",

    // Test
    testIntro: "Send a small sandbox payment to a test number. Nothing real is charged. When it completes, you've proved payments reach your own pawaPay account.",
    testPhone: "Phone number",
    testProvider: "Network",
    testAmount: "Amount (TZS)",
    sendTest: "Send test payment",
    sending: "Sending…",
    checkStatus: "Check status",
    testStatus: { pending: "Waiting for the payment to complete…", paid: "Test payment completed", failed: "Test payment failed" },
    tryAgain: "Try again",

    // Live
    liveIntro: "Last step. Connect your production token, then submit. Kampasika checks everything and switches you live.",
    waitingForKampasika: "Everything's in. Kampasika is reviewing — you'll get a notification.",
    needsSubmit: "Connect production, then submit for review from the home screen.",

    // Admin
    adminTitle: "Kampasika Biz — Admin",
    adminFilterAll: "All",
    adminEmpty: "No businesses yet.",
    adminApproveDocs: "Approve documents",
    adminRequestChanges: "Request changes",
    adminSetLive: "Set live",
    adminSuspend: "Pause",
    adminReopen: "Back to review",
    adminNote: "Note to the business (optional)",
    adminHelpConnect: "Help connect a token (in person)",
    adminOnlyNotice: "Only Kampasika admins can open this page.",
    lastUpdated: "Updated",


    // Navigation
    navSetup: "Setup",
    navApplications: "Applications",

    // Applications (step 2)
    applicationsTitle: "Applications",
    applicationsIntro: "Students apply for your rooms from Kampasika. Review them here and contact the ones you want.",
    applicationsLocked: "Applications open once Kampasika has approved your documents.",
    acceptingOn: "Accepting applications",
    acceptingOff: "Not accepting applications",
    acceptingHint: "When on, students see an “Apply” button on your rooms in Kampasika.",
    appFilters: { new: "New", shortlisted: "Shortlisted", approved: "Approved", closed: "Closed" },
    appStatus: { submitted: "New", shortlisted: "Shortlisted", approved: "Approved", rejected: "Rejected", withdrawn: "Withdrawn" },
    appEmpty: "No applications here yet.",
    appNewCount: "{count} new",
    appRoom: "Room",
    appMoveIn: "Move-in",
    appStay: "Stay",
    appStayOptions: { semester: "One semester", academic_year: "Academic year", monthly: "Month to month", other: "Other" },
    appUniversity: "University",
    appCourse: "Course / year",
    appReg: "Reg. number",
    appPhone: "Phone",
    appMessage: "Message",
    appApplied: "Applied",
    appCall: "Call",
    appWhatsApp: "WhatsApp",
    appShortlist: "Shortlist",
    appApprove: "Approve",
    appReject: "Reject",
    appNotePlaceholder: "Note to the student (optional)",
    appHistory: "History",
    appDecided: "Student notified.",
    appNextLease: "Next: leases for approved students are coming in the next update.",

    // Leases (step 3)
    navLeases: "Leases",
    leasesTitle: "Leases",
    leasesIntro: "Create a lease from an approved application. The student reads it and signs in Kampasika.",
    leasesEmpty: "No leases yet. Approve an application, then tap “Create lease”.",
    leaseStatus: { sent: "Waiting for signature", signed: "Signed", declined: "Declined", cancelled: "Cancelled" },
    leaseFilters: { sent: "Waiting", signed: "Signed", closed: "Closed" },
    templateCardTitle: "Your lease template",
    templateCardBody: "Start from the Kampasika standard lease and edit it to match your house rules.",
    templateStandard: "Standard lease",
    templateCustom: "Your edited lease",
    editTemplate: "Edit template",
    templateTitle: "Lease template",
    templateIntro: "Edit any clause, add your own or remove ones you don't need. Words in {{double braces}} are filled in automatically for each student.",
    templateLegalNote: "This standard lease is a plain-language starting point, not legal advice. Have a lawyer check it before you rely on it.",
    templateLanguage: "Lease language",
    languages: { en: "English", sw: "Kiswahili" },
    clauseTitle: "Heading",
    clauseBody: "Text",
    addClause: "+ Add clause",
    removeClause: "Remove",
    moveUp: "↑",
    moveDown: "↓",
    resetTemplate: "Reset to standard lease",
    placeholdersTitle: "Placeholders you can use",
    defaultsTitle: "Default terms",
    defaultsIntro: "Pre-filled on every new lease. You can still change them per student.",
    rentPeriod: "Rent period",
    rentPeriods: { month: "Per month", semester: "Per semester", year: "Per year" },
    rent: "Rent (TZS)",
    deposit: "Deposit (TZS)",
    dueDay: "Rent due by day",
    noticeDays: "Notice period (days)",
    utilities: "Water & electricity",
    utilitiesHint: "Completes “Water and electricity are …”, e.g. “included in the rent” or “paid by the tenant through their own LUKU meter”.",
    utilitiesHintSw: "Completes “Maji na umeme …”, e.g. “yamejumuishwa kwenye kodi”.",
    startDate: "Start date",
    endDate: "End date",
    extraTerms: "Extra terms for this student",
    createLease: "Create lease",
    createLeaseTitle: "New lease",
    createLeaseIntro: "Check the terms, preview, then send. The student gets a notification to read and sign.",
    preview: "Preview",
    sendLease: "Send lease to student",
    viewLease: "View lease",
    leaseFor: "Lease for {name}",
    leaseRef: "Lease {ref}",
    landlord: "Landlord",
    tenant: "Tenant",
    summary: "Summary",
    perPeriod: "per {period}",
    issuedBy: "Issued by {name} on {date}",
    signedBy: "Signed by {name} on {date}",
    signatureDetails: "Typed-name signature · version {hash}",
    printLease: "Print / save as PDF",
    cancelLease: "Withdraw lease",
    cancelReason: "Reason (optional)",
    signTitle: "Sign this lease",
    signIntro: "Read the whole lease first. Signing is binding — only sign if you agree with every clause.",
    agreeBox: "I have read this lease and I agree to its terms.",
    typeName: "Type your full name to sign",
    signButton: "Sign lease",
    signing: "Signing…",
    declineButton: "Decline",
    declineReason: "Tell the landlord why (optional)",
    declineConfirm: "Decline lease",
    signedBanner: "This lease is signed by both parties.",
    declinedBanner: "The student declined this lease.",
    cancelledBanner: "This lease was withdrawn by the landlord.",
    waitingBanner: "Waiting for the student to sign.",
    leaseNotFound: "This lease doesn't exist or isn't yours.",
    backToKampasika: "Back to Kampasika",
    applicationLease: "Lease",

    // Rent (step 4)
    navRent: "Rent",
    rentTitle: "Rent",
    rentIntro: "Every signed lease becomes a rent schedule. Students pay by mobile money straight to your pawaPay account; record cash or bank payments yourself.",
    tileCollected: "Collected this month",
    tileOutstanding: "Overdue balance",
    tileOverdue: "Tenants behind",
    tileDueSoon: "Due in 7 days",
    occupancyTitle: "Occupancy",
    occupied: "{occupied} of {total} rooms occupied",
    otherRooms: "Other rooms",
    noRooms: "No rooms listed yet. Add rooms in the Kampasika app (My Properties).",
    onlinePayTitle: "Online rent payments",
    onlinePayLive: "On — students pay into your production pawaPay account.",
    onlinePayOff: "Off — you'll go live after Kampasika's review. Until then, record payments yourself.",
    sandboxRentLabel: "Test mode: let students pay in the pawaPay sandbox",
    sandboxRentHint: "For trying the flow with test numbers only — no real money moves. Turn it off before real tenants pay.",
    chargeFilters: { overdue: "Overdue", soon: "Due soon", open: "All unpaid", paid: "Paid" },
    chargeStatus: { due: "Due", partial: "Part paid", paid: "Paid", waived: "Waived", overdue: "Overdue" },
    noCharges: "Nothing here.",
    dueOn: "Due {date}",
    balance: "Balance",
    paid: "Paid",
    payments: "Payments",
    recordPayment: "Record a payment",
    amount: "Amount (TZS)",
    method: "Method",
    methods: { cash: "Cash", bank: "Bank", mobile_money: "Mobile money (outside Kampasika)", other: "Other", pawapay: "pawaPay", pawapay_sandbox: "pawaPay (test)" },
    reference: "Reference / receipt no.",
    paidOn: "Paid on",
    waive: "Waive",
    waiveNote: "Reason (shown to the student)",
    rentScheduleTitle: "Rent & payments",
    payNow: "Pay",
    payTitle: "Pay with mobile money",
    payTestBadge: "TEST MODE — no real money",
    payNotAvailable: "Online payment isn't switched on for this landlord yet. Pay them directly — they'll record it here.",
    payPhone: "Your mobile money number",
    payNetwork: "Network",
    payAmount: "Amount (TZS)",
    paySend: "Send payment request",
    payWaiting: "Check your phone and approve the payment…",
    payDone: "Payment received ✓",
    payFailed: "The payment didn't go through.",
    totalDue: "Still to pay",
    genericError: "Something went wrong. Please try again.",
  },

  sw: {
    brand: "Kampasika Biz",
    tagline: "Endesha hosteli yako. Pokea malipo moja kwa moja kwenye akaunti yako.",
    back: "Rudi",
    save: "Hifadhi",
    saving: "Inahifadhi…",
    saved: "Imehifadhiwa",
    cancel: "Ghairi",
    continue: "Endelea",
    copy: "Nakili",
    copied: "Imenakiliwa",
    optional: "si lazima",
    loading: "Inapakia…",
    openKampasika: "Fungua Kampasika",
    language: "English",

    signInTitle: "Ingia kwa akaunti yako ya Kampasika",
    signInBody: "Kampasika Biz inatumia akaunti ile ile ya programu ya Kampasika. Ingia huko, kisha rudi kwenye ukurasa huu.",
    signInButton: "Nenda Kampasika kuingia",

    welcomeTitle: "Leta hosteli yako Kampasika Biz",
    welcomeBody: "Sajili biashara yako mara moja. Tunakusaidia kupata akaunti yako mwenyewe ya pawaPay, ili wanafunzi walipe kodi kwa simu na pesa ziingie moja kwa moja kwako — Kampasika haishiki pesa zako.",
    welcomePoints: [
      "Wanafunzi wanaona na kuomba vyumba vyako kwenye Kampasika",
      "Kodi inalipwa kwa M-Pesa, Airtel Money, Mixx by Yas au HaloPesa",
      "Pesa zinaingia kwenye akaunti yako, si yetu",
      "Ona nani amelipa na nani bado, kwa kila jengo",
    ],
    businessName: "Jina la biashara au hosteli",
    contactName: "Jina lako kamili",
    contactPhone: "Namba ya simu",
    startSetup: "Anza usajili",

    statusLabel: {
      draft: "Inaandaliwa",
      in_review: "Inakaguliwa",
      needs_changes: "Marekebisho yanahitajika",
      live: "Iko hewani",
      suspended: "Imesimamishwa",
    },
    progress: "Tayari {percent}%",
    checklistTitle: "Jiandae kupokea kodi",
    stepState: { done: "Imekamilika", waiting: "Inasubiri", todo: "Fanya", blocked: "Baadaye" },
    steps: {
      profile: { title: "Taarifa za biashara", body: "Jina, usajili, TIN na mawasiliano." },
      documents: { title: "Nyaraka", body: "Cheti cha BRELA, cheti cha TIN na kitambulisho cha mmiliki." },
      settlement: { title: "Pesa zinaingia wapi", body: "Akaunti ya benki au ya simu ambayo pawaPay itakulipa." },
      application: { title: "Omba pawaPay", body: "Fungua akaunti yako ya mfanyabiashara ya pawaPay." },
      sandbox: { title: "Unganisha sandbox", body: "Bandika tokeni ya majaribio (sandbox) ya pawaPay." },
      test: { title: "Tuma malipo ya majaribio", body: "Thibitisha malipo yanafika kwenye akaunti yako ya pawaPay." },
      live: { title: "Anza rasmi", body: "Unganisha tokeni ya production. Kampasika itakuwasha." },
    },
    submitForReview: "Tuma kwa Kampasika ikaguliwe",
    submitHint: "Kamilisha taarifa, nyaraka na akaunti ya malipo ili kutuma. Unaweza kuendelea na pawaPay tukiwa tunakagua.",
    submitted: "Imetumwa. Tutakagua biashara yako na kukujulisha hapa.",
    changesNeeded: "Kampasika imeomba marekebisho:",
    liveBanner: "Uko hewani. Kodi ya wanafunzi sasa inaingia moja kwa moja kwenye akaunti yako ya pawaPay.",
    suspendedBanner: "Akaunti yako ya Kampasika Biz imesimamishwa. Wasiliana na Kampasika.",

    businessType: "Aina ya biashara",
    businessTypes: { company: "Kampuni iliyosajiliwa", sole_proprietor: "Jina la biashara (mmiliki pekee)", individual: "Mmiliki binafsi" },
    brelaNumber: "Namba ya usajili BRELA",
    tin: "TIN",
    contactEmail: "Barua pepe",
    region: "Mkoa",
    area: "Eneo / mtaa",
    nearUni: "Chuo kilicho karibu",
    propertyCount: "Idadi ya hosteli / majengo",
    bedCount: "Jumla ya vitanda",
    requiredNote: "Sehemu zisizo na “si lazima” zinahitajika na pawaPay na Kampasika.",

    docTypes: {
      brela: { title: "Cheti cha BRELA", body: "Cheti cha usajili wa kampuni au jina la biashara." },
      tin: { title: "Cheti cha TIN", body: "Kutoka TRA." },
      ownerId: { title: "Kitambulisho cha mmiliki", body: "NIDA, pasipoti au leseni ya udereva ya mmiliki / mkurugenzi." },
      licence: { title: "Leseni ya biashara", body: "Kama unayo." },
    },
    upload: "Pakia",
    replace: "Badilisha",
    uploading: "Inapakia…",
    view: "Tazama",
    notRequired: "Haihitajiki kwa aina ya biashara yako",
    fileRules: "Picha au PDF, hadi MB 10.",
    fileBadType: "Tafadhali chagua picha au PDF.",
    fileTooBig: "Faili hilo ni zaidi ya MB 10.",
    docsReview: { approved: "Imeidhinishwa na Kampasika", changes_requested: "Kampasika imeomba upakie tena", pending: "Inasubiri ukaguzi wa Kampasika" },

    settlementIntro: "pawaPay inalipa pesa zilizokusanywa kwenye akaunti hii. Kampasika inaiandika hapa tu ili tukusaidie — akaunti yenyewe inasajiliwa na pawaPay.",
    settlementMethod: "Aina ya akaunti ya kupokea",
    settlementMethods: { bank: "Akaunti ya benki", mobile_money: "Pochi ya pesa ya simu" },
    institution: "Benki au mtandao",
    institutionPlaceholder: "mf. CRDB, NMB, NBC, M-Pesa",
    accountName: "Jina la akaunti",
    accountNameHint: "Lilingane na jina la biashara au la mmiliki.",
    confirmedWithPawapay: "Nitampa pawaPay taarifa hizi hizi za akaunti",
    noAccountNumber: "Hatuombi namba ya akaunti yako — hiyo inaenda kwa pawaPay pekee.",

    applicationIntro: "pawaPay inafungua akaunti za wafanyabiashara kwa biashara zilizosajiliwa na zinazofuata taratibu. Akaunti ni yako: kodi inaingia kwako, na unaona kila malipo kwenye dashibodi yako ya pawaPay.",
    applicationChecklistTitle: "Andaa hivi unapoomba",
    applicationChecklist: [
      "Usajili wako wa BRELA na TIN",
      "Kitambulisho cha mmiliki / mkurugenzi",
      "Akaunti ya kupokea kutoka hatua iliyopita",
      "Maelezo mafupi: malazi ya wanafunzi, kukusanya kodi kwa pesa ya simu",
    ],
    applicationHowTitle: "Inavyokwenda",
    applicationHow: [
      "Omba kwenye pawapay.io na ukamilishe ukaguzi wao wa biashara.",
      "pawaPay itakupa ufikiaji wa sandbox (majaribio) — uunganishe hatua inayofuata.",
      "Ukiidhinishwa, pawaPay itakupa tokeni ya production kwa pesa halisi.",
    ],
    applicationConfirmNote: "Mahitaji ya pawaPay yanaweza kubadilika — fuata wanachokuomba timu yao.",
    openPawapay: "Fungua pawapay.io",
    applicationStatus: "Umefika wapi na pawaPay?",
    applicationStatuses: { not_started: "Bado sijaomba", submitted: "Nimeomba, nasubiri pawaPay", approved: "Nimeidhinishwa na pawaPay" },
    merchantName: "Jina la mfanyabiashara kwenye pawaPay",
    applicationNote: "Maelezo (namba ya kumbukumbu, mtu wa mawasiliano…)",

    sandboxIntro: "Kwenye dashibodi ya sandbox ya pawaPay, tengeneza API token na uibandike hapa. Tunaikagua na pawaPay, kisha tunaihifadhi kwa usimbaji fiche — hakuna mtu Kampasika anayeweza kuisoma.",
    productionIntro: "pawaPay ikikuidhinisha kwa malipo halisi, tengeneza API token ya production na uibandike hapa.",
    apiToken: "API token",
    connect: "Unganisha",
    connecting: "Inakagua na pawaPay…",
    connectedAs: "Imeunganishwa kama {name}",
    connectedToken: "Tokeni inayoishia …{last4}",
    disconnect: "Tenganisha",
    callbackTitle: "Weka callback URL",
    callbackBody: "Kwenye dashibodi ya pawaPay, weka deposit callback URL kuwa anwani hii ili malipo yasasishwe hapa yenyewe:",
    signedCallbacksOff: "Kidokezo: malipo yanasasishwa hata bila callback — unaweza kubonyeza “Angalia hali” kwenye malipo yoyote.",

    testIntro: "Tuma malipo madogo ya sandbox kwa namba ya majaribio. Hakuna pesa halisi inayokatwa. Yakikamilika, umethibitisha malipo yanafika kwenye akaunti yako ya pawaPay.",
    testPhone: "Namba ya simu",
    testProvider: "Mtandao",
    testAmount: "Kiasi (TZS)",
    sendTest: "Tuma malipo ya majaribio",
    sending: "Inatuma…",
    checkStatus: "Angalia hali",
    testStatus: { pending: "Inasubiri malipo yakamilike…", paid: "Malipo ya majaribio yamekamilika", failed: "Malipo ya majaribio yameshindwa" },
    tryAgain: "Jaribu tena",

    liveIntro: "Hatua ya mwisho. Unganisha tokeni ya production, kisha tuma. Kampasika itakagua kila kitu na kukuwasha.",
    waitingForKampasika: "Kila kitu kimekamilika. Kampasika inakagua — utapata taarifa.",
    needsSubmit: "Unganisha production, kisha tuma ikaguliwe kutoka ukurasa wa mwanzo.",

    adminTitle: "Kampasika Biz — Admin",
    adminFilterAll: "Zote",
    adminEmpty: "Bado hakuna biashara.",
    adminApproveDocs: "Idhinisha nyaraka",
    adminRequestChanges: "Omba marekebisho",
    adminSetLive: "Washa",
    adminSuspend: "Simamisha",
    adminReopen: "Rudisha ukaguzini",
    adminNote: "Ujumbe kwa biashara (si lazima)",
    adminHelpConnect: "Saidia kuunganisha tokeni (ana kwa ana)",
    adminOnlyNotice: "Ni admin wa Kampasika pekee wanaoweza kufungua ukurasa huu.",
    lastUpdated: "Imesasishwa",


    navSetup: "Usajili",
    navApplications: "Maombi",

    applicationsTitle: "Maombi",
    applicationsIntro: "Wanafunzi wanaomba vyumba vyako kupitia Kampasika. Yakague hapa na uwasiliane na unaowataka.",
    applicationsLocked: "Maombi yanafunguliwa baada ya Kampasika kuidhinisha nyaraka zako.",
    acceptingOn: "Unapokea maombi",
    acceptingOff: "Hupokei maombi",
    acceptingHint: "Ukiwasha, wanafunzi wanaona kitufe cha “Omba” kwenye vyumba vyako Kampasika.",
    appFilters: { new: "Mapya", shortlisted: "Waliochaguliwa", approved: "Yaliyokubaliwa", closed: "Yaliyofungwa" },
    appStatus: { submitted: "Jipya", shortlisted: "Amechaguliwa", approved: "Limekubaliwa", rejected: "Limekataliwa", withdrawn: "Limeondolewa" },
    appEmpty: "Bado hakuna maombi hapa.",
    appNewCount: "{count} mapya",
    appRoom: "Chumba",
    appMoveIn: "Kuhamia",
    appStay: "Muda",
    appStayOptions: { semester: "Semester moja", academic_year: "Mwaka wa masomo", monthly: "Kila mwezi", other: "Nyingine" },
    appUniversity: "Chuo",
    appCourse: "Kozi / mwaka",
    appReg: "Namba ya usajili",
    appPhone: "Simu",
    appMessage: "Ujumbe",
    appApplied: "Aliomba",
    appCall: "Piga simu",
    appWhatsApp: "WhatsApp",
    appShortlist: "Chagua awali",
    appApprove: "Kubali",
    appReject: "Kataa",
    appNotePlaceholder: "Ujumbe kwa mwanafunzi (si lazima)",
    appHistory: "Historia",
    appDecided: "Mwanafunzi amejulishwa.",
    appNextLease: "Ifuatayo: mikataba kwa wanafunzi waliokubaliwa inakuja kwenye toleo lijalo.",

    navLeases: "Mikataba",
    leasesTitle: "Mikataba",
    leasesIntro: "Tengeneza mkataba kutoka kwenye ombi lililokubaliwa. Mwanafunzi anausoma na kuusaini ndani ya Kampasika.",
    leasesEmpty: "Bado hakuna mikataba. Kubali ombi, kisha bonyeza “Tengeneza mkataba”.",
    leaseStatus: { sent: "Unasubiri sahihi", signed: "Umesainiwa", declined: "Umekataliwa", cancelled: "Umefutwa" },
    leaseFilters: { sent: "Inasubiri", signed: "Imesainiwa", closed: "Imefungwa" },
    templateCardTitle: "Kiolezo chako cha mkataba",
    templateCardBody: "Anza na mkataba wa kawaida wa Kampasika na uuhariri ulingane na kanuni za nyumba yako.",
    templateStandard: "Mkataba wa kawaida",
    templateCustom: "Mkataba wako uliohariri",
    editTemplate: "Hariri kiolezo",
    templateTitle: "Kiolezo cha mkataba",
    templateIntro: "Hariri kifungu chochote, ongeza vyako au ondoa usivyohitaji. Maneno ndani ya {{mabano mawili}} yanajazwa yenyewe kwa kila mwanafunzi.",
    templateLegalNote: "Mkataba huu wa kawaida ni mwanzo kwa lugha rahisi, si ushauri wa kisheria. Mwombe mwanasheria aukague kabla ya kuutegemea.",
    templateLanguage: "Lugha ya mkataba",
    languages: { en: "English", sw: "Kiswahili" },
    clauseTitle: "Kichwa",
    clauseBody: "Maandishi",
    addClause: "+ Ongeza kifungu",
    removeClause: "Ondoa",
    moveUp: "↑",
    moveDown: "↓",
    resetTemplate: "Rudisha mkataba wa kawaida",
    placeholdersTitle: "Maneno ya kujazwa unayoweza kutumia",
    defaultsTitle: "Masharti ya kawaida",
    defaultsIntro: "Yanajazwa kwenye kila mkataba mpya. Bado unaweza kuyabadilisha kwa kila mwanafunzi.",
    rentPeriod: "Kipindi cha kodi",
    rentPeriods: { month: "Kwa mwezi", semester: "Kwa semester", year: "Kwa mwaka" },
    rent: "Kodi (TZS)",
    deposit: "Amana (TZS)",
    dueDay: "Kodi ilipwe kabla ya siku",
    noticeDays: "Muda wa taarifa (siku)",
    utilities: "Maji na umeme",
    utilitiesHint: "Inakamilisha “Water and electricity are …”, mf. “included in the rent”.",
    utilitiesHintSw: "Inakamilisha “Maji na umeme …”, mf. “yamejumuishwa kwenye kodi” au “yanalipwa na mpangaji kupitia mita yake ya LUKU”.",
    startDate: "Tarehe ya kuanza",
    endDate: "Tarehe ya kuisha",
    extraTerms: "Masharti ya ziada kwa mwanafunzi huyu",
    createLease: "Tengeneza mkataba",
    createLeaseTitle: "Mkataba mpya",
    createLeaseIntro: "Kagua masharti, angalia hakikisho, kisha tuma. Mwanafunzi atapata taarifa ya kuusoma na kuusaini.",
    preview: "Hakikisho",
    sendLease: "Tuma mkataba kwa mwanafunzi",
    viewLease: "Tazama mkataba",
    leaseFor: "Mkataba wa {name}",
    leaseRef: "Mkataba {ref}",
    landlord: "Mwenye Nyumba",
    tenant: "Mpangaji",
    summary: "Muhtasari",
    perPeriod: "kwa {period}",
    issuedBy: "Umetolewa na {name} tarehe {date}",
    signedBy: "Umesainiwa na {name} tarehe {date}",
    signatureDetails: "Sahihi kwa kuandika jina · toleo {hash}",
    printLease: "Chapisha / hifadhi PDF",
    cancelLease: "Futa mkataba",
    cancelReason: "Sababu (si lazima)",
    signTitle: "Saini mkataba huu",
    signIntro: "Soma mkataba wote kwanza. Kusaini kunakufunga kisheria — saini tu kama unakubali kila kifungu.",
    agreeBox: "Nimesoma mkataba huu na ninakubali masharti yake.",
    typeName: "Andika jina lako kamili kusaini",
    signButton: "Saini mkataba",
    signing: "Inasaini…",
    declineButton: "Kataa",
    declineReason: "Mweleze mwenye nyumba sababu (si lazima)",
    declineConfirm: "Kataa mkataba",
    signedBanner: "Mkataba huu umesainiwa na pande zote mbili.",
    declinedBanner: "Mwanafunzi amekataa mkataba huu.",
    cancelledBanner: "Mkataba huu umefutwa na mwenye nyumba.",
    waitingBanner: "Unasubiri mwanafunzi asaini.",
    leaseNotFound: "Mkataba huu haupo au si wako.",
    backToKampasika: "Rudi Kampasika",
    applicationLease: "Mkataba",

    navRent: "Kodi",
    rentTitle: "Kodi",
    rentIntro: "Kila mkataba uliosainiwa unakuwa ratiba ya kodi. Wanafunzi wanalipa kwa pesa ya simu moja kwa moja kwenye akaunti yako ya pawaPay; andika mwenyewe malipo ya taslimu au benki.",
    tileCollected: "Zilizokusanywa mwezi huu",
    tileOutstanding: "Deni lililochelewa",
    tileOverdue: "Wapangaji waliochelewa",
    tileDueSoon: "Zinadaiwa ndani ya siku 7",
    occupancyTitle: "Ukaliaji",
    occupied: "Vyumba {occupied} kati ya {total} vimekaliwa",
    otherRooms: "Vyumba vingine",
    noRooms: "Bado hakuna vyumba. Ongeza vyumba kwenye programu ya Kampasika (My Properties).",
    onlinePayTitle: "Malipo ya kodi mtandaoni",
    onlinePayLive: "Yamewashwa — wanafunzi wanalipa kwenye akaunti yako ya production ya pawaPay.",
    onlinePayOff: "Yamezimwa — utawashwa baada ya ukaguzi wa Kampasika. Hadi hapo, andika malipo mwenyewe.",
    sandboxRentLabel: "Hali ya majaribio: wanafunzi walipe kwenye sandbox ya pawaPay",
    sandboxRentHint: "Kwa kujaribu tu kwa namba za majaribio — hakuna pesa halisi inayohamishwa. Zima kabla wapangaji halisi hawajalipa.",
    chargeFilters: { overdue: "Zimechelewa", soon: "Zinakaribia", open: "Zote zisizolipwa", paid: "Zimelipwa" },
    chargeStatus: { due: "Inadaiwa", partial: "Imelipwa sehemu", paid: "Imelipwa", waived: "Imesamehewa", overdue: "Imechelewa" },
    noCharges: "Hakuna kitu hapa.",
    dueOn: "Inadaiwa {date}",
    balance: "Salio",
    paid: "Imelipwa",
    payments: "Malipo",
    recordPayment: "Andika malipo",
    amount: "Kiasi (TZS)",
    method: "Njia",
    methods: { cash: "Taslimu", bank: "Benki", mobile_money: "Pesa ya simu (nje ya Kampasika)", other: "Nyingine", pawapay: "pawaPay", pawapay_sandbox: "pawaPay (majaribio)" },
    reference: "Kumbukumbu / namba ya risiti",
    paidOn: "Tarehe ya malipo",
    waive: "Samehe",
    waiveNote: "Sababu (mwanafunzi ataiona)",
    rentScheduleTitle: "Kodi na malipo",
    payNow: "Lipa",
    payTitle: "Lipa kwa pesa ya simu",
    payTestBadge: "MAJARIBIO — hakuna pesa halisi",
    payNotAvailable: "Malipo mtandaoni bado hayajawashwa kwa mwenye nyumba huyu. Mlipe moja kwa moja — ataandika hapa.",
    payPhone: "Namba yako ya pesa ya simu",
    payNetwork: "Mtandao",
    payAmount: "Kiasi (TZS)",
    paySend: "Tuma ombi la malipo",
    payWaiting: "Angalia simu yako na uidhinishe malipo…",
    payDone: "Malipo yamepokelewa ✓",
    payFailed: "Malipo hayakufanikiwa.",
    totalDue: "Bado kulipa",
    genericError: "Kuna tatizo. Tafadhali jaribu tena.",
  },
};

export function t(lang, key, vars) {
  const table = COPY[lang] || COPY.en;
  const value = key.split(".").reduce((obj, part) => (obj == null ? obj : obj[part]), table);
  const fallback = key.split(".").reduce((obj, part) => (obj == null ? obj : obj[part]), COPY.en);
  const out = value ?? fallback ?? key;
  if (typeof out !== "string" || !vars) return out;
  return out.replace(/\{(\w+)\}/g, (_, name) => (vars[name] ?? ""));
}
